import type { SemanticDataset, SemanticField } from "@/store/datasetSlice"

/** Datasets built through the canvas (CTE/SQL-defined), not pulled from a source. */
export function isCreatedDataset(dataset: SemanticDataset): boolean {
  return (
    dataset.source_kind === "custom" ||
    dataset.metadata?.source_type === "custom" ||
    dataset.metadata?.source === "canvas"
  )
}

/** Fields added through the canvas rather than autogenerated from columns. */
export function isCreatedField(field: SemanticField): boolean {
  return field.metadata?.source === "canvas"
}
