import type { SemanticDataset, SemanticField } from "@/store/datasetSlice"

/** Datasets built through custom SQL/canvas, not pulled directly from a stock source table. */
export function isCustomDataset(dataset: SemanticDataset): boolean {
  return (
    dataset.source_kind === "custom" ||
    dataset.metadata?.source_type === "custom" ||
    dataset.metadata?.source === "canvas"
  )
}

/** Fields added through the canvas on stock datasets rather than autogenerated from columns. */
export function isCustomField(field: SemanticField): boolean {
  return field.metadata?.source === "canvas"
}
