const assert = require('node:assert/strict');
const test = require('node:test');
const { prepareClaude, finishClaude } = require('./ocr-workflow.cjs');
const { encodeState, readState } = require('./ocr-state.cjs');
const HEAD='a'.repeat(40), BASE='b'.repeat(40), POLICY='c'.repeat(64);
function harness() {
 const h={ env:{PR_NUMBER:'42',REVIEW_HEAD:HEAD,REVIEW_BASE:BASE,POLICY,GITHUB_REPOSITORY:'owner/repo',GITHUB_SERVER_URL:'https://github.com',GITHUB_RUN_ATTEMPT:'1',RUNNER_TEMP:'/tmp',CLAUDE_OUTCOME:'success',CLAUDE_CONCLUSION:'success',CLAUDE_RESULT:JSON.stringify({complete:true,reviewed_head:HEAD,blocking_findings:0}),EXECUTION_FILE:'/sdk.json'},context:{repo:{owner:'owner',repo:'repo'},runId:123},outputs:{},files:{'/sdk.json':JSON.stringify([{type:'result',subtype:'success',is_error:false,permission_denials:[]}])},writes:[],failures:[],pr:{state:'open',head:{sha:HEAD},base:{sha:BASE}}};
 h.comments=[{id:1,user:{login:'github-actions[bot]',type:'Bot'},body:'<!-- scout-ocr-gate -->\nOriginal OCR explanation\n'+encodeState({version:1,head:HEAD,base:BASE,policy:POLICY,run:'123',passed:true,claudeHead:null})}];
 h.core={setOutput:(k,v)=>h.outputs[k]=v,info(){},warning(){},setFailed:r=>h.failures.push(r),summary:{addRaw(s){h.summary=s;return this;},async write(){}}};
 h.fs={writeFileSync:(p,s)=>h.files[p]=s,readFileSync:p=>{if(!(p in h.files))throw Error('PRIVATE PATH');return h.files[p];}};
 const publish=async p=>{if(h.publishError)throw Error('PRIVATE MESSAGE');h.writes.push(p);const id=p.comment_id||100+h.comments.length;const value={id,user:{login:'github-actions[bot]',type:'Bot'},body:p.body};h.comments=h.comments.filter(c=>c.id!==id).concat(value);return {data:value};};
 h.github={rest:{issues:{listComments(){},createComment:publish,updateComment:publish},pulls:{get:async()=>({data:h.pr}),listReviewComments(){},listReviews(){}}},paginate:async method=>method===h.github.rest.issues.listComments?h.comments:[]};
 return h;
}
async function prepared() {const h=harness();await prepareClaude(h);h.env.CLAUDE_RECEIPT=h.outputs.receipt;h.env.BASELINE_ISSUE_IDS=h.outputs.issue_ids;return h;}
function reviewed(h){h.comments.push({id:500,user:{login:'github-actions[bot]',type:'Bot'},body:'No blocking findings after reviewing the exact range.\n<!-- scout-claude-artifact:v1 '+h.env.CLAUDE_RECEIPT+' -->'});}
test('prepare emits unique run-bound receipt and pending status with fixed prefetch',async()=>{const h=await prepared();const r=JSON.parse(h.env.CLAUDE_RECEIPT);assert.equal(r.run,'123');assert.equal(r.attempt,'1');assert.equal(r.head,HEAD);assert.match(r.nonce,/^[a-f0-9]{64}$/);assert.match(h.comments.find(c=>c.body.startsWith('<!-- scout-claude-review -->')).body,/pending/);const other=await prepared();assert.notEqual(other.outputs.receipt,h.outputs.receipt);});
test('verified receipt is published before accepted Claude checkpoint advances',async()=>{const h=await prepared();reviewed(h);h.writes=[];await finishClaude(h);assert.deepEqual(h.failures,[]);assert.equal(readState(h.comments).claudeHead,HEAD);assert.match(h.writes[0].body,/Claude review: verified/);assert.match(h.writes.at(-1).body,/Original OCR explanation/);assert.equal(h.outputs.claude_verified,'true');});
test('failed action, missing SDK, malformed output and absent artifact visibly block',async()=>{for(const mutate of [h=>h.env.CLAUDE_OUTCOME='failure',h=>delete h.files['/sdk.json'],h=>h.env.CLAUDE_RESULT='PRIVATE malformed',h=>h.comments=h.comments.filter(c=>c.id!==500)]){const h=await prepared();reviewed(h);mutate(h);await finishClaude(h);assert.ok(h.failures.length);assert.equal(readState(h.comments).claudeHead,null);assert.match(h.summary,/blocked/);assert.doesNotMatch(h.summary,/PRIVATE/);assert.notEqual(h.outputs.claude_verified,'true');}});
test('positive blocking findings and changed base never advance checkpoint',async()=>{for(const mutate of [h=>h.env.CLAUDE_RESULT=JSON.stringify({complete:true,reviewed_head:HEAD,blocking_findings:1}),h=>h.pr.base.sha=HEAD]){const h=await prepared();reviewed(h);mutate(h);await finishClaude(h);assert.equal(readState(h.comments).claudeHead,null);assert.ok(h.failures.length);assert.match(h.summary,/blocked/);}});
test('publication failure cannot advance checkpoint or disclose exception content',async()=>{const h=await prepared();reviewed(h);h.publishError=true;await finishClaude(h);assert.equal(readState(h.comments).claudeHead,null);assert.ok(h.failures.length);assert.doesNotMatch(h.failures.join(),/PRIVATE/);assert.notEqual(h.outputs.claude_verified,'true');});
test('late older attempt never overwrites a newer pending receipt',async()=>{const h=await prepared();reviewed(h);const newer={...h,env:{...h.env,GITHUB_RUN_ATTEMPT:'2'}};await prepareClaude(newer);const pending=h.comments.find(c=>c.body.startsWith('<!-- scout-claude-review -->')).body;h.writes=[];await finishClaude(h);assert.equal(h.writes.length,0);assert.equal(h.comments.find(c=>c.body.startsWith('<!-- scout-claude-review -->')).body,pending);assert.equal(readState(h.comments).claudeHead,null);});
