"""Tests for the thread-bound semantic canvas changeset."""

import pytest

from apps.chat.models import Thread
from apps.semantic.canvas import (
    apply_operations,
    canvas_projection,
    commit_canvas,
    resolve_thread_canvas,
)
from apps.semantic.canvas import commit as canvas_commit_module
from apps.semantic.canvas import service as canvas_service
from apps.semantic.models import (
    CustomDataset,
    SemanticCanvasChange,
    SemanticDataset,
    SemanticField,
    SemanticModel,
    SemanticRelationship,
)
from apps.semantic.services import catalog as catalog_service
from apps.semantic.services.catalog import PhysicalTable
from apps.semantic.services.cube import generate_cube_schema


@pytest.fixture
def semantic_model(workspace):
    model = SemanticModel.objects.create(workspace=workspace, name="Model")
    visits = SemanticDataset.objects.create(
        semantic_model=model,
        workspace=workspace,
        name="raw_visits",
        label="Visits",
        table_name="raw_visits",
        schema_name="tenant_schema",
        primary_key="visit_id",
    )
    users = SemanticDataset.objects.create(
        semantic_model=model,
        workspace=workspace,
        name="raw_users",
        label="Users",
        table_name="raw_users",
        schema_name="tenant_schema",
        primary_key="username",
    )
    for dataset, column, data_type in (
        (visits, "visit_id", "bigint"),
        (visits, "username", "text"),
        (visits, "amount", "numeric"),
        (users, "username", "text"),
    ):
        SemanticField.objects.create(
            dataset=dataset,
            name=column,
            field_type=SemanticField.FieldType.DIMENSION,
            data_type=data_type,
            expression=column,
            metadata={"source_column": column},
        )
    SemanticField.objects.create(
        dataset=visits,
        name="count",
        field_type=SemanticField.FieldType.MEASURE,
        data_type="integer",
        expression="*",
        measure_type=SemanticField.MeasureType.COUNT,
        metadata={"generated": True},
    )
    return model


@pytest.fixture
def canvas(workspace, user, semantic_model):
    thread = Thread.objects.create(workspace=workspace, user=user)
    return resolve_thread_canvas(workspace, thread, user)


def _visits(semantic_model):
    return semantic_model.datasets.get(name="raw_visits")


def test_apply_stages_dataset_edit_with_minimal_delta(canvas, semantic_model):
    result = apply_operations(
        canvas,
        [
            {"op": "add_existing", "object_type": "dataset", "ref": "raw_visits"},
            {"op": "set", "target": "dataset/raw_visits/description", "value": "All visits"},
        ],
    )

    assert "errors" not in result
    change = canvas.changes.get()
    assert change.change_type == SemanticCanvasChange.ChangeType.UPDATE
    assert change.fields == {"description": "All visits"}
    projection = canvas_projection(canvas)
    entry = projection["objects"][0]
    assert entry["state"] == "edited"
    assert entry["diff"]["description"]["to"] == "All visits"
    assert projection["can_commit"] is True

    # Setting the value back to base removes the delta -> membership row.
    apply_operations(
        canvas, [{"op": "set", "target": "dataset/raw_visits/description", "value": ""}]
    )
    change.refresh_from_db()
    assert change.fields == {}
    assert canvas_projection(canvas)["objects"][0]["state"] == "unchanged"


def test_batch_is_atomic_on_invalid_op(canvas):
    result = apply_operations(
        canvas,
        [
            {"op": "set", "target": "dataset/raw_visits/description", "value": "kept?"},
            {"op": "set", "target": "dataset/raw_visits/name", "value": "nope"},
        ],
    )

    assert result["errors"][0]["code"] == "INVALID_TARGET"
    assert result["errors"][0]["op_index"] == 1
    assert canvas.changes.count() == 0


def test_autogenerated_fields_are_protected(canvas, semantic_model):
    field = _visits(semantic_model).fields.get(name="amount")

    curate = apply_operations(
        canvas, [{"op": "set", "target": f"field/{field.id}/description", "value": "USD"}]
    )
    assert "errors" not in curate

    retype = apply_operations(
        canvas, [{"op": "set", "target": "field/raw_visits.amount/expression", "value": "x"}]
    )
    assert retype["errors"][0]["code"] == "PROTECTED_FIELD"

    delete = apply_operations(
        canvas, [{"op": "delete_object", "object": "field/raw_visits.amount"}]
    )
    assert delete["errors"][0]["code"] == "PROTECTED_FIELD"

    physical = apply_operations(
        canvas, [{"op": "delete_object", "object": "dataset/raw_visits"}]
    )
    assert physical["errors"][0]["code"] == "PROTECTED_OBJECT"


def test_canvas_curates_field_display_metadata(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {"op": "set", "target": "field/raw_visits.amount/format", "value": "decimal_02"},
            {"op": "set", "target": "field/raw_visits.amount/currency", "value": "usd"},
        ],
        user,
    )

    assert "errors" not in result
    entry = next(obj for obj in result["objects"] if obj["name"] == "amount")
    assert entry["diff"]["format"]["to"] == "number_2"
    assert entry["diff"]["currency"]["to"] == "USD"

    report = commit_canvas(canvas, user)

    assert report["blocked"] is False
    field = _visits(semantic_model).fields.get(name="amount")
    assert field.metadata["format"] == "number_2"
    assert field.metadata["currency"] == "USD"
    assert {"format", "currency"} <= set(field.metadata["curated_fields"])

    cube = next(c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits")
    amount_dimension = next(d for d in cube["dimensions"] if d["name"] == "amount")
    assert amount_dimension["format"] == "number_2"
    assert amount_dimension["currency"] == "USD"


def test_created_measure_supports_count_distinct(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "distinct_workers",
                    "field_type": "measure",
                    "measure_type": "count_distinct",
                    "expression": "username",
                },
            }
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    field = _visits(semantic_model).fields.get(name="distinct_workers")
    assert field.measure_type == "count_distinct"

    cube = next(c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits")
    measure = next(m for m in cube["measures"] if m["name"] == "distinct_workers")
    assert measure == {
        "name": "distinct_workers",
        "type": "count_distinct",
        "sql": '{CUBE}."username"',
    }


def test_created_measure_supports_cube_filters(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "paid_visit_count",
                    "field_type": "measure",
                    "measure_type": "count",
                    "filter": {"sql": '{CUBE}."amount" > 0'},
                },
            }
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    field = _visits(semantic_model).fields.get(name="paid_visit_count")
    assert field.metadata["filters"] == [{"sql": '{CUBE}."amount" > 0'}]

    cube = next(c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits")
    measure = next(m for m in cube["measures"] if m["name"] == "paid_visit_count")
    assert measure == {
        "name": "paid_visit_count",
        "type": "count",
        "filters": [{"sql": '{CUBE}."amount" > 0'}],
    }


def test_created_measure_supports_calculated_cube_sql(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "amount_per_visit",
                    "field_type": "measure",
                    "measure_type": "number",
                    "sql": "{count} / NULLIF({count}, 0)",
                    "format": "currency_2",
                    "currency": "usd",
                },
            }
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    field = _visits(semantic_model).fields.get(name="amount_per_visit")
    assert field.expression == ""
    assert field.metadata["cube_sql"] == "{count} / NULLIF({count}, 0)"

    cube = next(c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits")
    measure = next(m for m in cube["measures"] if m["name"] == "amount_per_visit")
    assert measure == {
        "name": "amount_per_visit",
        "type": "number",
        "sql": "{count} / NULLIF({count}, 0)",
        "format": "currency_2",
        "currency": "USD",
    }


def test_measure_options_are_structural_for_generated_fields(canvas, semantic_model):
    result = apply_operations(
        canvas,
        [
            {
                "op": "set",
                "target": "field/raw_visits.count/filters",
                "value": [{"sql": '{CUBE}."amount" > 0'}],
            }
        ],
    )

    assert result["errors"][0]["code"] == "PROTECTED_FIELD"


def test_created_measure_validates_expression_column(canvas):
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "total_bogus",
                    "field_type": "measure",
                    "measure_type": "sum",
                    "expression": "not_a_column",
                },
            }
        ],
    )

    assert "errors" not in result
    codes = {d["code"] for d in result["diagnostics"]}
    assert "UNKNOWN_COLUMN" in codes
    assert result["can_commit"] is False

    report = commit_canvas(canvas)
    assert report["blocked"] is True
    assert report["committed"] == []


def test_commit_creates_field_and_marks_canvas_source(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "total_amount",
                    "label": "Total Amount",
                    "field_type": "measure",
                    "measure_type": "sum",
                    "expression": "amount",
                },
            }
        ],
        user,
    )

    report = commit_canvas(canvas, user)

    assert report["blocked"] is False
    assert len(report["committed"]) == 1
    assert report["committed"][0]["name"] == "total_amount"
    field = _visits(semantic_model).fields.get(name="total_amount")
    assert field.metadata["source"] == "canvas"
    assert field.measure_type == "sum"
    # Settled create rows become membership rows and stay on the canvas.
    change = canvas.changes.get(object_uuid=field.id)
    assert change.change_type == SemanticCanvasChange.ChangeType.UPDATE
    assert change.fields == {}
    assert canvas_projection(canvas)["objects"][0]["state"] == "unchanged"


def test_commit_creates_relationship_with_join_expression(canvas, workspace, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "relationship",
                "value": {
                    "from_dataset": "raw_visits",
                    "from_field": "username",
                    "to_dataset": "raw_users",
                    "to_field": "username",
                    "relationship_type": "many_to_one",
                },
            }
        ],
        user,
    )
    assert result["diagnostics"] == []

    commit_canvas(canvas, user)

    relationship = SemanticRelationship.objects.get(workspace=workspace)
    assert relationship.join_expression == "{raw_visits.username} = {raw_users.username}"
    assert relationship.metadata["source"] == "canvas"


def test_relationship_from_pk_less_dataset_is_blocked(canvas, semantic_model, user):
    visits = _visits(semantic_model)
    visits.primary_key = ""
    visits.save()

    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "relationship",
                "value": {
                    "from_dataset": "raw_visits",
                    "from_field": "username",
                    "to_dataset": "raw_users",
                    "to_field": "username",
                    "relationship_type": "many_to_one",
                },
            }
        ],
        user,
    )

    codes = {d["code"] for d in result["diagnostics"]}
    assert "MISSING_PRIMARY_KEY" in codes
    report = commit_canvas(canvas, user)
    assert report["blocked"] is True


def test_custom_dataset_draft_and_commit(canvas, semantic_model, workspace, monkeypatch, user):
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )

    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "visit_stats",
                    "label": "Visit Stats",
                    "primary_key": "username",
                    "definition_sql": (
                        "with s as (select username, count(*) as visit_count "
                        "from raw_visits group by username) select * from s"
                    ),
                },
            }
        ],
        user,
    )
    assert result["diagnostics"] == []
    draft = canvas.changes.get()
    assert draft.fields["_validation"]["columns"][0]["name"] == "username"
    assert 'from "raw_visits"' in draft.fields["_validation"]["compiled_sql"]

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    custom = CustomDataset.objects.get(workspace=workspace, name="visit_stats")
    dataset = semantic_model.datasets.get(name="visit_stats")
    assert dataset.source_kind == SemanticDataset.SourceKind.CUSTOM
    assert dataset.custom_dataset_id == custom.id
    assert dataset.metadata["source"] == "canvas"
    assert dataset.primary_key == "username"
    assert dataset.fields.filter(name="username", is_visible=True).exists()
    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "visit_stats"
    )
    assert cube["sql"] == dataset.metadata["cube_sql"]


def test_custom_dataset_fields_can_be_deleted_and_stay_hidden(
    canvas, semantic_model, monkeypatch, user
):
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "visit_stats",
                    "primary_key": "username",
                    "definition_sql": "select username, count(*) as visit_count from raw_visits group by username",
                },
            }
        ],
        user,
    )
    assert commit_canvas(canvas, user)["blocked"] is False

    dataset = semantic_model.datasets.get(name="visit_stats")
    assert dataset.fields.filter(name="visit_count", is_visible=True).exists()
    assert dataset.fields.filter(name="sum_visit_count", is_visible=True).exists()

    result = apply_operations(
        canvas,
        [
            {"op": "delete_object", "object": "field/visit_stats.visit_count"},
            {"op": "delete_object", "object": "field/visit_stats.sum_visit_count"},
        ],
        user,
    )

    assert "errors" not in result
    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    hidden_dimension = dataset.fields.get(name="visit_count")
    hidden_measure = dataset.fields.get(name="sum_visit_count")
    assert hidden_dimension.is_visible is False
    assert hidden_measure.is_visible is False
    assert "is_visible" in hidden_dimension.metadata["curated_fields"]
    assert "is_visible" in hidden_measure.metadata["curated_fields"]

    catalog_service._sync_fields(
        dataset,
        [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
        None,
    )
    hidden_dimension.refresh_from_db()
    hidden_measure.refresh_from_db()
    assert hidden_dimension.is_visible is False
    assert hidden_measure.is_visible is False


def test_custom_dataset_requires_primary_key(canvas, monkeypatch, user):
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "no_pk_stats",
                    "definition_sql": "select username, count(*) as visit_count from raw_visits group by username",
                },
            }
        ],
        user,
    )

    codes = {d["code"] for d in result["diagnostics"]}
    assert "MISSING_PRIMARY_KEY" in codes
    assert commit_canvas(canvas, user)["blocked"] is True

    # An `id` output column is accepted as the default primary key.
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [{"name": "id", "type": "bigint"}],
    )
    apply_operations(canvas, [{"op": "revert_object", "object": "custom_dataset/no_pk_stats"}], user)
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {"name": "id_stats", "definition_sql": "select visit_id as id from raw_visits"},
            }
        ],
        user,
    )
    assert result["diagnostics"] == []


def test_primary_key_editable_on_custom_datasets_only(canvas, semantic_model, workspace, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "pk_stats",
                    "primary_key": "username",
                    "definition_sql": "select username, count(*) as visit_count from raw_visits group by username",
                },
            }
        ],
        user,
    )
    commit_canvas(canvas, user)

    changed = apply_operations(
        canvas, [{"op": "set", "target": "dataset/pk_stats/primary_key", "value": "visit_count"}], user
    )
    assert "errors" not in changed
    commit_canvas(canvas, user)
    assert semantic_model.datasets.get(name="pk_stats").primary_key == "visit_count"

    unknown = apply_operations(
        canvas, [{"op": "set", "target": "dataset/pk_stats/primary_key", "value": "nope"}], user
    )
    assert unknown["errors"][0]["code"] == "UNKNOWN_COLUMN"

    physical = apply_operations(
        canvas, [{"op": "set", "target": "dataset/raw_visits/primary_key", "value": "username"}], user
    )
    assert physical["errors"][0]["code"] == "INVALID_TARGET"


def test_fallback_primary_key_for_base_tables_only():
    columns = [{"name": "id", "type": "bigint"}, {"name": "value", "type": "text"}]
    assert catalog_service._fallback_primary_key("table", columns) == "id"
    assert catalog_service._fallback_primary_key("view", columns) == ""
    assert catalog_service._fallback_primary_key("table", [{"name": "value"}]) == ""


def test_invalid_custom_sql_blocks_commit(canvas, user):
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {"name": "bad_stats", "definition_sql": "drop table raw_visits"},
            }
        ],
        user,
    )
    codes = {d["code"] for d in result["diagnostics"]}
    assert "INVALID_SQL" in codes
    report = commit_canvas(canvas, user)
    assert report["blocked"] is True


def test_conflict_detected_when_base_moves(canvas, semantic_model, user):
    apply_operations(
        canvas,
        [{"op": "set", "target": "dataset/raw_visits/description", "value": "draft"}],
        user,
    )
    visits = _visits(semantic_model)
    visits.label = "Visits (renamed elsewhere)"
    visits.save()

    projection = canvas_projection(canvas)
    assert projection["objects"][0]["state"] == "conflict"
    report = commit_canvas(canvas, user)
    assert report["committed"] == []
    assert report["conflicts"]

    # revert_object picks up the current persisted version again.
    apply_operations(canvas, [{"op": "revert_object", "object": "dataset/raw_visits"}], user)
    assert canvas_projection(canvas)["objects"][0]["state"] == "unchanged"


def test_refresh_preserves_curated_and_canvas_fields(
    canvas, semantic_model, workspace, monkeypatch, user
):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    apply_operations(
        canvas,
        [
            {"op": "set", "target": "dataset/raw_visits/label", "value": "Curated Visits"},
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "total_amount",
                    "field_type": "measure",
                    "measure_type": "sum",
                    "expression": "amount",
                },
            },
        ],
        user,
    )
    commit_canvas(canvas, user)

    monkeypatch.setattr(
        catalog_service,
        "load_physical_tables",
        lambda _workspace: (
            "tenant_schema",
            [
                PhysicalTable(
                    name="raw_visits",
                    type="table",
                    description="Visits",
                    columns=[
                        {"name": "visit_id", "type": "bigint"},
                        {"name": "username", "type": "text"},
                        {"name": "amount", "type": "numeric"},
                    ],
                    primary_key="visit_id",
                ),
            ],
        ),
    )
    monkeypatch.setattr(catalog_service, "get_registry", lambda: _empty_registry())

    catalog_service.ensure_semantic_model(workspace)

    visits = workspace.semantic_datasets.get(name="raw_visits")
    assert visits.label == "Curated Visits"
    assert "label" in visits.metadata["curated_fields"]
    canvas_field = visits.fields.get(name="total_amount")
    assert canvas_field.is_visible is True
    assert canvas_field.metadata["source"] == "canvas"


def _empty_registry():
    class _Registry:
        def list(self):
            return []

    return _Registry()


def test_can_write_canvas_matches_rest_policy(workspace, user, read_user):
    from apps.agents.tools.canvas_tool import can_write_canvas

    assert can_write_canvas(workspace, user) is True
    assert can_write_canvas(workspace, read_user) is False
    assert can_write_canvas(workspace, None) is False


@pytest.mark.asyncio
@pytest.mark.django_db(transaction=True)
async def test_canvas_write_tools_forbidden_for_read_role(workspace, read_user, semantic_model):
    from apps.agents.tools.canvas_tool import create_canvas_tools

    thread = await Thread.objects.acreate(workspace=workspace, user=read_user)
    tools = {t.name: t for t in create_canvas_tools(workspace, read_user, str(thread.id))}

    apply_result = await tools["canvas_apply"].ainvoke(
        {"operations": [{"op": "add_existing", "object_type": "dataset", "ref": "raw_visits"}]}
    )
    assert apply_result["errors"][0]["code"] == "FORBIDDEN"

    commit_result = await tools["canvas_commit"].ainvoke({})
    assert commit_result["errors"][0]["code"] == "FORBIDDEN"

    assert await SemanticCanvasChange.objects.acount() == 0
    # Reads stay available to read-only members, matching the REST policy.
    read_result = await tools["canvas_read"].ainvoke({"selector": "graph"})
    assert "Canvas is empty" in read_result


@pytest.mark.django_db
def test_build_tools_gates_canvas_manager_on_write_role(workspace, user):
    from apps.agents.graph.base import _build_tools

    writable = {
        t.name
        for t in _build_tools(
            workspace, user, [], conversation_id="t1", interactive=True, canvas_write=True
        )
    }
    assert {"canvas_read", "canvas_manager"} <= writable

    readonly = {
        t.name
        for t in _build_tools(
            workspace, user, [], conversation_id="t1", interactive=True, canvas_write=False
        )
    }
    assert "canvas_read" in readonly
    assert "canvas_manager" not in readonly


@pytest.mark.django_db
def test_thread_canvas_api_flow(client, workspace, user, semantic_model):
    client.force_login(user)
    thread = Thread.objects.create(workspace=workspace, user=user)
    base = f"/api/workspaces/{workspace.id}/threads/{thread.id}/canvas/"

    projection = client.get(base).json()
    assert projection["objects"] == []
    assert projection["can_commit"] is False

    response = client.post(
        f"{base}apply/",
        {
            "operations": [
                {"op": "set", "target": "dataset/raw_visits/description", "value": "All visits"}
            ]
        },
        content_type="application/json",
    )
    assert response.status_code == 200
    assert response.json()["objects"][0]["state"] == "edited"

    bad = client.post(
        f"{base}apply/",
        {"operations": [{"op": "set", "target": "dataset/raw_visits/nope", "value": "x"}]},
        content_type="application/json",
    )
    assert bad.status_code == 400
    assert bad.json()["errors"][0]["code"] == "INVALID_TARGET"


@pytest.mark.django_db
def test_thread_canvas_api_requires_write_role(client, workspace, read_user, semantic_model):
    client.force_login(read_user)
    thread = Thread.objects.create(workspace=workspace, user=read_user)
    base = f"/api/workspaces/{workspace.id}/threads/{thread.id}/canvas/"

    assert client.get(base).status_code == 200
    response = client.post(f"{base}apply/", {"operations": []}, content_type="application/json")
    assert response.status_code == 403


@pytest.mark.django_db
def test_thread_canvas_api_rejects_foreign_thread(client, workspace, user, read_user, semantic_model):
    client.force_login(user)
    foreign = Thread.objects.create(workspace=workspace, user=read_user)
    response = client.get(f"/api/workspaces/{workspace.id}/threads/{foreign.id}/canvas/")
    assert response.status_code == 404
