"""Tests for the thread-bound semantic canvas changeset."""

import asyncio
import json
import uuid
from concurrent.futures import ThreadPoolExecutor
from datetime import timedelta
from threading import Event
from types import SimpleNamespace
from unittest.mock import Mock

import pytest
from django.db import connections, transaction
from langchain_core.messages import AIMessage, ToolMessage

from apps.agents.tools.canvas_manager_agent import create_canvas_manager_tool
from apps.agents.tools.canvas_tool import create_canvas_tools
from apps.chat.models import Thread
from apps.semantic.canvas import (
    apply_operations,
    canvas_projection,
    commit_canvas,
    resolve_thread_canvas,
)
from apps.semantic.canvas import commit as canvas_commit_module
from apps.semantic.canvas import service as canvas_service
from apps.semantic.canvas.projections import render_projection_text
from apps.semantic.models import (
    CubeSchema,
    CustomDataset,
    SemanticCanvasChange,
    SemanticDataset,
    SemanticField,
    SemanticModel,
    SemanticRelationship,
)
from apps.semantic.services import catalog as catalog_service
from apps.semantic.services.catalog import PhysicalTable
from apps.semantic.services.cube import generate_cube_schema


@pytest.fixture
def semantic_model(workspace):
    model = SemanticModel.objects.create(workspace=workspace, name="Model")
    visits = SemanticDataset.objects.create(
        semantic_model=model,
        workspace=workspace,
        name="raw_visits",
        label="Visits",
        table_name="raw_visits",
        schema_name="tenant_schema",
        primary_key="visit_id",
    )
    users = SemanticDataset.objects.create(
        semantic_model=model,
        workspace=workspace,
        name="raw_users",
        label="Users",
        table_name="raw_users",
        schema_name="tenant_schema",
        primary_key="username",
    )
    for dataset, column, data_type in (
        (visits, "visit_id", "bigint"),
        (visits, "username", "text"),
        (visits, "amount", "numeric"),
        (users, "username", "text"),
    ):
        SemanticField.objects.create(
            dataset=dataset,
            name=column,
            field_type=SemanticField.FieldType.DIMENSION,
            data_type=data_type,
            expression=column,
            metadata={"source_column": column},
        )
    SemanticField.objects.create(
        dataset=visits,
        name="count",
        field_type=SemanticField.FieldType.MEASURE,
        data_type="integer",
        expression="*",
        measure_type=SemanticField.MeasureType.COUNT,
        metadata={"generated": True},
    )
    return model


@pytest.fixture
def canvas(workspace, user, semantic_model):
    thread = Thread.objects.create(workspace=workspace, user=user)
    return resolve_thread_canvas(workspace, thread, user)


def _visits(semantic_model):
    return semantic_model.datasets.get(name="raw_visits")


def test_apply_stages_dataset_edit_with_minimal_delta(canvas, semantic_model):
    result = apply_operations(
        canvas,
        [
            {"op": "add_existing", "object_type": "dataset", "ref": "raw_visits"},
            {"op": "set", "target": "dataset/raw_visits/description", "value": "All visits"},
        ],
    )

    assert "errors" not in result
    change = canvas.changes.get()
    assert change.change_type == SemanticCanvasChange.ChangeType.UPDATE
    assert change.fields == {"description": "All visits"}
    projection = canvas_projection(canvas)
    entry = projection["objects"][0]
    assert entry["state"] == "edited"
    assert entry["diff"]["description"]["to"] == "All visits"
    assert projection["can_commit"] is True

    # Setting the value back to base removes the delta -> membership row.
    apply_operations(
        canvas, [{"op": "set", "target": "dataset/raw_visits/description", "value": ""}]
    )
    change.refresh_from_db()
    assert change.fields == {}
    assert canvas_projection(canvas)["objects"][0]["state"] == "unchanged"


def test_batch_is_atomic_on_invalid_op(canvas):
    result = apply_operations(
        canvas,
        [
            {"op": "set", "target": "dataset/raw_visits/description", "value": "kept?"},
            {"op": "set", "target": "dataset/raw_visits/name", "value": "nope"},
        ],
    )

    assert result["errors"][0]["code"] == "INVALID_TARGET"
    assert result["errors"][0]["op_index"] == 1
    assert canvas.changes.count() == 0


def test_autogenerated_fields_are_protected(canvas, semantic_model):
    field = _visits(semantic_model).fields.get(name="amount")

    curate = apply_operations(
        canvas, [{"op": "set", "target": f"field/{field.id}/description", "value": "USD"}]
    )
    assert "errors" not in curate

    retype = apply_operations(
        canvas, [{"op": "set", "target": "field/raw_visits.amount/expression", "value": "x"}]
    )
    assert retype["errors"][0]["code"] == "PROTECTED_FIELD"

    delete = apply_operations(
        canvas, [{"op": "delete_object", "object": "field/raw_visits.amount"}]
    )
    assert delete["errors"][0]["code"] == "PROTECTED_FIELD"

    physical = apply_operations(canvas, [{"op": "delete_object", "object": "dataset/raw_visits"}])
    assert physical["errors"][0]["code"] == "PROTECTED_OBJECT"


def test_canvas_curates_field_display_metadata(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {"op": "set", "target": "field/raw_visits.amount/format", "value": "decimal_02"},
            {"op": "set", "target": "field/raw_visits.amount/currency", "value": "usd"},
        ],
        user,
    )

    assert "errors" not in result
    entry = next(obj for obj in result["objects"] if obj["name"] == "amount")
    assert entry["diff"]["format"]["to"] == "number_2"
    assert entry["diff"]["currency"]["to"] == "USD"

    report = commit_canvas(canvas, user)

    assert report["blocked"] is False
    field = _visits(semantic_model).fields.get(name="amount")
    assert field.metadata["format"] == "number_2"
    assert field.metadata["currency"] == "USD"
    assert {"format", "currency"} <= set(field.metadata["curated_fields"])

    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    amount_dimension = next(d for d in cube["dimensions"] if d["name"] == "amount")
    assert amount_dimension["format"] == "number_2"
    assert amount_dimension["currency"] == "USD"


def test_created_measure_supports_count_distinct(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "distinct_workers",
                    "field_type": "measure",
                    "measure_type": "count_distinct",
                    "expression": "username",
                },
            }
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    field = _visits(semantic_model).fields.get(name="distinct_workers")
    assert field.measure_type == "count_distinct"

    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    measure = next(m for m in cube["measures"] if m["name"] == "distinct_workers")
    assert measure == {
        "name": "distinct_workers",
        "type": "count_distinct",
        "sql": '{CUBE}."username"',
    }


def test_created_measure_supports_cube_filters(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "paid_visit_count",
                    "field_type": "measure",
                    "measure_type": "count",
                    "filter": {"sql": '{CUBE}."amount" > 0'},
                },
            }
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    field = _visits(semantic_model).fields.get(name="paid_visit_count")
    assert field.metadata["filters"] == [{"sql": '{CUBE}."amount" > 0'}]

    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    measure = next(m for m in cube["measures"] if m["name"] == "paid_visit_count")
    assert measure == {
        "name": "paid_visit_count",
        "type": "count",
        "filters": [{"sql": '{CUBE}."amount" > 0'}],
    }


def test_created_measure_supports_calculated_cube_sql(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "amount_per_visit",
                    "field_type": "measure",
                    "measure_type": "number",
                    "sql": "{count}::numeric / NULLIF({count}, 0)",
                    "format": "currency_2",
                    "currency": "usd",
                },
            }
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    field = _visits(semantic_model).fields.get(name="amount_per_visit")
    assert field.expression == ""
    assert field.metadata["cube_sql"] == "{count}::numeric / NULLIF({count}, 0)"

    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    measure = next(m for m in cube["measures"] if m["name"] == "amount_per_visit")
    assert measure == {
        "name": "amount_per_visit",
        "type": "number",
        "sql": "{count}::numeric / NULLIF({count}, 0)",
        "format": "currency_2",
        "currency": "USD",
    }

    regression = apply_operations(
        canvas,
        [
            {
                "op": "set",
                "target": "field/raw_visits.amount_per_visit/cube_sql",
                "value": "{count} / NULLIF({count}, 0)",
            }
        ],
        user,
    )
    assert regression["can_commit"] is False
    assert regression["diagnostics"][0]["code"] == "INTEGER_DIVISION_RISK"


@pytest.mark.parametrize("field_type", ["dimension", "time_dimension"])
@pytest.mark.parametrize("sql_key", ["sql", "cube_sql"])
def test_calculated_dimension_create_commit_and_query_sql(
    canvas, semantic_model, monkeypatch, user, field_type, sql_key
):
    monkeypatch.setattr(
        canvas_commit_module,
        "build_and_promote_cube_schema",
        lambda ws, model: SimpleNamespace(content_hash="calculated-dimension-test"),
    )
    calculation = (
        "CASE WHEN {CUBE}.\"amount\" > 0 THEN 'Paid' ELSE 'Unpaid' END"
        if field_type == "dimension"
        else "CASE WHEN {CUBE}.\"amount\" > 0 THEN DATE '2026-09-01' ELSE NULL END"
    )
    before = list(_visits(semantic_model).fields.values())
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "paid_period",
                    "field_type": field_type,
                    "data_type": "text" if field_type == "dimension" else "date",
                    sql_key: calculation,
                },
            }
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []
    assert result["can_commit"] is True
    assert commit_canvas(canvas, user)["blocked"] is False
    field = _visits(semantic_model).fields.get(name="paid_period")
    assert field.expression == ""
    assert field.metadata["cube_sql"] == calculation
    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    dimension = next(d for d in cube["dimensions"] if d["name"] == "paid_period")
    assert '{CUBE}."amount"' in dimension["sql"]
    assert '{CUBE}.""' not in dimension["sql"]
    assert dimension["type"] == ("time" if field_type == "time_dimension" else "string")
    assert list(_visits(semantic_model).fields.exclude(id=field.id).values()) == before
    catalog_service._sync_fields(
        _visits(semantic_model),
        [
            {"name": "visit_id", "type": "bigint"},
            {"name": "username", "type": "text"},
            {"name": "amount", "type": "numeric"},
        ],
        None,
    )
    field.refresh_from_db()
    assert field.is_visible and field.metadata["cube_sql"] == calculation


def test_calculated_dimension_set_repairs_saved_field_and_clear_requires_column(
    canvas, semantic_model, monkeypatch, user
):
    monkeypatch.setattr(
        canvas_commit_module,
        "build_and_promote_cube_schema",
        lambda ws, model: SimpleNamespace(content_hash="calculated-dimension-test"),
    )
    field = SemanticField.objects.create(
        dataset=_visits(semantic_model),
        name="amount_band",
        field_type="dimension",
        data_type="text",
        expression="",
        metadata={"source": "canvas", "cube_sql": "'Old'"},
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "set",
                "target": "field/raw_visits.amount_band/sql",
                "value": "CASE WHEN amount > 0 THEN 'Paid' ELSE 'Unpaid' END",
            }
        ],
        user,
    )
    assert result["diagnostics"] == []
    assert commit_canvas(canvas, user)["blocked"] is False
    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    assert '{CUBE}."amount"' in next(
        d["sql"] for d in cube["dimensions"] if d["name"] == field.name
    )

    cleared = apply_operations(
        canvas, [{"op": "set", "target": "field/raw_visits.amount_band/sql", "value": ""}]
    )
    assert cleared["can_commit"] is False
    assert "MISSING_EXPRESSION" in {d["code"] for d in cleared["diagnostics"]}
    assert commit_canvas(canvas, user)["blocked"] is True
    field.refresh_from_db()
    assert field.metadata["cube_sql"]

    repaired = apply_operations(
        canvas,
        [{"op": "set", "target": "field/raw_visits.amount_band/expression", "value": "amount"}],
    )
    assert repaired["diagnostics"] == []
    assert commit_canvas(canvas, user)["blocked"] is False
    field.refresh_from_db()
    assert field.expression == "amount" and "cube_sql" not in field.metadata


@pytest.mark.parametrize("value", ["", "unknown_column"])
def test_canvas_created_dimension_update_validates_expression(canvas, semantic_model, value):
    SemanticField.objects.create(
        dataset=_visits(semantic_model),
        name="amount_copy",
        field_type="dimension",
        data_type="numeric",
        expression="amount",
        metadata={"source": "canvas"},
    )
    result = apply_operations(
        canvas, [{"op": "set", "target": "field/raw_visits.amount_copy/expression", "value": value}]
    )
    assert result["can_commit"] is False
    assert commit_canvas(canvas)["blocked"] is True


def test_dimension_filters_cannot_be_added_through_set(canvas, semantic_model):
    SemanticField.objects.create(
        dataset=_visits(semantic_model),
        name="amount_copy",
        field_type="dimension",
        data_type="numeric",
        expression="amount",
        metadata={"source": "canvas"},
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "set",
                "target": "field/raw_visits.amount_copy/filters",
                "value": [{"sql": "amount > 0"}],
            }
        ],
    )
    assert result["can_commit"] is False
    assert "INVALID_FIELD_OPTION" in {d["code"] for d in result["diagnostics"]}
    assert commit_canvas(canvas)["blocked"] is True


def test_calculated_dimension_cannot_become_a_primary_key_by_column_fallback(semantic_model):
    SemanticField.objects.create(
        dataset=_visits(semantic_model),
        name="visit_bucket",
        field_type="dimension",
        data_type="numeric",
        expression="visit_id",
        metadata={"source": "canvas", "cube_sql": '{CUBE}."visit_id" % 2'},
    )
    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    dimension = next(d for d in cube["dimensions"] if d["name"] == "visit_bucket")
    assert "primary_key" not in dimension


@pytest.mark.parametrize(
    "calculation",
    [
        "CASE WHEN unknown_column > 0 THEN 'Paid' END",
        "COUNT(*)",
        "pg_sleep(1)",
        "(SELECT username FROM raw_users)",
        "{count}",
    ],
)
@pytest.mark.parametrize("operation", ["create", "set_draft", "set_saved"])
def test_calculated_dimension_invalid_sql_blocks_all_authoring_paths(
    canvas, semantic_model, calculation, operation
):
    if operation == "create":
        operations = [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "amount_band",
                    "field_type": "dimension",
                    "data_type": "text",
                    "sql": calculation,
                },
            }
        ]
    else:
        if operation == "set_saved":
            SemanticField.objects.create(
                dataset=_visits(semantic_model),
                name="amount_band",
                field_type="dimension",
                data_type="text",
                expression="amount",
                metadata={"source": "canvas"},
            )
        else:
            result = apply_operations(
                canvas,
                [
                    {
                        "op": "create",
                        "object_type": "field",
                        "value": {
                            "dataset": "raw_visits",
                            "name": "amount_band",
                            "field_type": "dimension",
                            "data_type": "text",
                            "expression": "amount",
                        },
                    }
                ],
            )
            assert "errors" not in result
        operations = [
            {"op": "set", "target": "field/raw_visits.amount_band/sql", "value": calculation}
        ]
    result = apply_operations(canvas, operations)
    assert "errors" not in result
    assert result["can_commit"] is False
    assert "INVALID_DIMENSION_SQL" in {d["code"] for d in result["diagnostics"]}
    assert commit_canvas(canvas)["blocked"] is True


@pytest.mark.parametrize("value", [0, 1, False, True, [], {}, ["amount"], {"sql": "amount"}])
def test_calculated_dimension_sql_type_is_validated(canvas, value):
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "amount_band",
                    "field_type": "dimension",
                    "data_type": "text",
                    "sql": value,
                },
            }
        ],
    )
    assert result["errors"][0]["code"] == "INVALID_CUBE_SQL"
    assert canvas.changes.count() == 0


def test_calculated_sql_stays_protected_on_generated_dimensions(canvas):
    result = apply_operations(
        canvas, [{"op": "set", "target": "field/raw_visits.username/sql", "value": "'Hidden'"}]
    )
    assert result["errors"][0]["code"] == "PROTECTED_FIELD"


def test_saved_invalid_dimension_sql_cannot_be_promoted_by_compiler(semantic_model):
    SemanticField.objects.create(
        dataset=_visits(semantic_model),
        name="amount_band",
        field_type="dimension",
        expression="",
        metadata={"source": "canvas", "cube_sql": "pg_sleep(1)"},
    )
    with pytest.raises(ValueError, match="not allowed"):
        generate_cube_schema(semantic_model)


def test_draft_column_dimension_can_be_converted_to_calculated_dimension(
    canvas, semantic_model, user, monkeypatch
):
    monkeypatch.setattr(
        canvas_commit_module,
        "build_and_promote_cube_schema",
        lambda ws, model: SimpleNamespace(content_hash="calculated-dimension-test"),
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "amount_band",
                    "field_type": "dimension",
                    "expression": "amount",
                    "data_type": "text",
                },
            },
            {
                "op": "set",
                "target": "field/raw_visits.amount_band/sql",
                "value": "CASE WHEN amount > 0 THEN 'Paid' ELSE 'Unpaid' END",
            },
        ],
        user,
    )
    assert result["can_commit"] and not result["diagnostics"]
    assert commit_canvas(canvas, user)["cube_schema"]["ok"]
    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    assert next(d["sql"] for d in cube["dimensions"] if d["name"] == "amount_band").startswith(
        "CASE WHEN"
    )


def test_created_ratio_measure_can_reference_filtered_measure(
    canvas,
    semantic_model,
    monkeypatch,
    user,
):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "approved_visit_count",
                    "field_type": "measure",
                    "measure_type": "count",
                    "filters": [{"sql": "{CUBE}.\"status\" = 'approved'"}],
                },
            },
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "approval_rate",
                    "field_type": "measure",
                    "measure_type": "number",
                    "sql": "{approved_visit_count}::numeric / NULLIF({count}, 0)",
                    "format": "percent_1",
                },
            },
        ],
        user,
    )

    assert "errors" not in result
    assert result["diagnostics"] == []
    assert commit_canvas(canvas, user)["blocked"] is False

    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "raw_visits"
    )
    measures = {measure["name"]: measure for measure in cube["measures"]}
    assert measures["approved_visit_count"]["filters"] == [
        {"sql": "{CUBE}.\"status\" = 'approved'"}
    ]
    assert measures["approval_rate"] == {
        "name": "approval_rate",
        "type": "number",
        "sql": "{approved_visit_count}::numeric / NULLIF({count}, 0)",
        "format": "percent_1",
    }


def test_created_ratio_measure_rejects_integer_division(canvas, user):
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "broken_rate",
                    "field_type": "measure",
                    "measure_type": "number",
                    "sql": "{count} / NULLIF({count}, 0)",
                },
            }
        ],
        user,
    )

    assert result["can_commit"] is False
    assert result["diagnostics"][0]["code"] == "INTEGER_DIVISION_RISK"


def test_measure_options_are_structural_for_generated_fields(canvas, semantic_model):
    result = apply_operations(
        canvas,
        [
            {
                "op": "set",
                "target": "field/raw_visits.count/filters",
                "value": [{"sql": '{CUBE}."amount" > 0'}],
            }
        ],
    )

    assert result["errors"][0]["code"] == "PROTECTED_FIELD"


def test_created_measure_validates_expression_column(canvas):
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "total_bogus",
                    "field_type": "measure",
                    "measure_type": "sum",
                    "expression": "not_a_column",
                },
            }
        ],
    )

    assert "errors" not in result
    codes = {d["code"] for d in result["diagnostics"]}
    assert "UNKNOWN_COLUMN" in codes
    assert result["can_commit"] is False

    report = commit_canvas(canvas)
    assert report["blocked"] is True
    assert report["committed"] == []


def test_commit_creates_field_and_marks_canvas_source(canvas, semantic_model, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "total_amount",
                    "label": "Total Amount",
                    "field_type": "measure",
                    "measure_type": "sum",
                    "expression": "amount",
                },
            }
        ],
        user,
    )

    report = commit_canvas(canvas, user)

    assert report["blocked"] is False
    assert len(report["committed"]) == 1
    assert report["committed"][0]["name"] == "total_amount"
    field = _visits(semantic_model).fields.get(name="total_amount")
    assert field.metadata["source"] == "canvas"
    assert field.measure_type == "sum"
    # Settled create rows become membership rows and stay on the canvas.
    change = canvas.changes.get(object_uuid=field.id)
    assert change.change_type == SemanticCanvasChange.ChangeType.UPDATE
    assert change.fields == {}
    assert canvas_projection(canvas)["objects"][0]["state"] == "unchanged"


def test_commit_creates_relationship_with_join_expression(canvas, workspace, monkeypatch, user):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "relationship",
                "value": {
                    "from_dataset": "raw_visits",
                    "from_field": "username",
                    "to_dataset": "raw_users",
                    "to_field": "username",
                    "relationship_type": "many_to_one",
                },
            }
        ],
        user,
    )
    assert result["diagnostics"] == []

    commit_canvas(canvas, user)

    relationship = SemanticRelationship.objects.get(workspace=workspace)
    assert relationship.join_expression == "{raw_visits.username} = {raw_users.username}"
    assert relationship.metadata["source"] == "canvas"


def test_relationship_from_pk_less_dataset_is_blocked(canvas, semantic_model, user):
    visits = _visits(semantic_model)
    visits.primary_key = ""
    visits.save()

    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "relationship",
                "value": {
                    "from_dataset": "raw_visits",
                    "from_field": "username",
                    "to_dataset": "raw_users",
                    "to_field": "username",
                    "relationship_type": "many_to_one",
                },
            }
        ],
        user,
    )

    codes = {d["code"] for d in result["diagnostics"]}
    assert "MISSING_PRIMARY_KEY" in codes
    report = commit_canvas(canvas, user)
    assert report["blocked"] is True


def test_custom_dataset_draft_and_commit(canvas, semantic_model, workspace, monkeypatch, user):
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )

    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "visit_stats",
                    "label": "Visit Stats",
                    "primary_key": "username",
                    "definition_sql": (
                        "with s as (select username, count(*) as visit_count "
                        "from raw_visits group by username) select * from s"
                    ),
                },
            }
        ],
        user,
    )
    assert result["diagnostics"] == []
    draft = canvas.changes.get()
    assert draft.fields["_validation"]["columns"][0]["name"] == "username"
    assert 'FROM "raw_visits"' in draft.fields["_validation"]["compiled_sql"]

    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    custom = CustomDataset.objects.get(workspace=workspace, name="visit_stats")
    dataset = semantic_model.datasets.get(name="visit_stats")
    assert dataset.source_kind == SemanticDataset.SourceKind.CUSTOM
    assert dataset.custom_dataset_id == custom.id
    assert dataset.metadata["source"] == "canvas"
    assert dataset.primary_key == "username"
    assert dataset.fields.filter(name="username", is_visible=True).exists()
    cube = next(
        c for c in generate_cube_schema(semantic_model)["cubes"] if c["name"] == "visit_stats"
    )
    assert cube["sql"] == (
        f"SELECT * FROM (\n{dataset.metadata['cube_sql']}\n) AS scout_source\n"
        "WHERE ARRAY[{SECURITY_CONTEXT.cubeDataRevision}]::text[] IS NOT NULL"
    )


@pytest.fixture
def pending_dataset_op(monkeypatch):
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        Mock(return_value=[{"name": "username", "type": "text"}]),
    )
    return {
        "op": "create",
        "object_type": "custom_dataset",
        "value": {
            "name": "visit_stats",
            "primary_key": "username",
            "definition_sql": "select distinct username from raw_visits",
        },
    }


def _refresh_canvas_catalog(workspace, monkeypatch, names):
    tables = [
        PhysicalTable(
            name=name,
            type="table",
            description="",
            columns=[{"name": "username", "type": "text"}],
            primary_key="username",
        )
        for name in names
    ]
    monkeypatch.setattr(catalog_service, "load_physical_tables", lambda ws: ("new_schema", tables))
    return catalog_service.ensure_semantic_model(workspace)


def test_canvas_revalidates_unchanged_sql_after_catalog_refresh(
    canvas, workspace, pending_dataset_op, monkeypatch
):
    apply_operations(canvas, [pending_dataset_op])
    probe = canvas_service.infer_custom_dataset_columns
    assert probe.call_count == 1
    canvas_projection(canvas)
    assert probe.call_count == 1
    revision = canvas.changes.get().fields["_validation"]["catalog_revision"]

    refreshed = _refresh_canvas_catalog(workspace, monkeypatch, ["raw_users"])
    assert refreshed.id == canvas.semantic_model_id
    removed = canvas_projection(canvas)
    assert removed["can_commit"] is False
    assert any("raw_visits" in d["message"] for d in removed["diagnostics"])
    assert canvas.changes.get().fields["_validation"]["catalog_revision"] != revision
    assert probe.call_count == 1  # Removed source is rejected before a DB probe.

    _refresh_canvas_catalog(workspace, monkeypatch, ["raw_users", "raw_visits"])
    restored = canvas_projection(canvas)
    assert restored["can_commit"] is True
    assert restored["diagnostics"] == []
    assert probe.call_count == 2


def test_canvas_refresh_reinfers_changed_columns(
    canvas, workspace, pending_dataset_op, monkeypatch
):
    apply_operations(canvas, [pending_dataset_op])
    canvas_service.infer_custom_dataset_columns.return_value = [
        {"name": "username", "type": "bigint"}
    ]
    _refresh_canvas_catalog(workspace, monkeypatch, ["raw_visits"])
    result = canvas_projection(canvas)
    assert result["objects"][0]["fields"]["columns"] == [{"name": "username", "type": "bigint"}]


def test_canvas_publishes_with_refreshed_model_version(
    canvas, workspace, pending_dataset_op, monkeypatch, user
):
    apply_operations(canvas, [pending_dataset_op])
    refreshed = _refresh_canvas_catalog(workspace, monkeypatch, ["raw_visits"])
    assert refreshed.version > canvas.semantic_model.version
    publisher = Mock()
    monkeypatch.setattr(canvas_commit_module, "build_and_promote_cube_schema", publisher)
    assert commit_canvas(canvas, user)["blocked"] is False
    assert publisher.call_args.kwargs["model"].version == refreshed.version


def test_canvas_failed_probe_retries_after_polling_ttl(canvas, pending_dataset_op, monkeypatch):
    now = canvas_service.timezone.now()
    canvas_service.infer_custom_dataset_columns.side_effect = [
        RuntimeError("temporary outage"),
        [{"name": "username", "type": "text"}],
    ]
    initial = apply_operations(canvas, [pending_dataset_op])
    assert initial["can_commit"] is False
    validation_time = canvas.changes.get().updated_at
    for _ in range(3):
        assert canvas_projection(canvas)["can_commit"] is False
    assert canvas_service.infer_custom_dataset_columns.call_count == 1
    assert canvas.changes.get().updated_at == validation_time
    monkeypatch.setattr(
        canvas_service.timezone,
        "now",
        lambda: now + timedelta(seconds=canvas_service.CUSTOM_DATASET_FAILURE_CACHE_SECONDS + 1),
    )
    assert canvas_projection(canvas)["can_commit"] is True
    assert canvas_service.infer_custom_dataset_columns.call_count == 2


def test_canvas_commit_retries_failed_probe_without_waiting_for_ttl(
    canvas, pending_dataset_op, monkeypatch, user
):
    canvas_service.infer_custom_dataset_columns.side_effect = [
        RuntimeError("temporary outage"),
        [{"name": "username", "type": "text"}],
    ]
    monkeypatch.setattr(canvas_commit_module, "build_and_promote_cube_schema", Mock())
    assert apply_operations(canvas, [pending_dataset_op])["can_commit"] is False
    assert commit_canvas(canvas, user)["blocked"] is False
    assert canvas_service.infer_custom_dataset_columns.call_count == 2


def test_cube_status_updates_do_not_invalidate_canvas_validation(
    canvas, pending_dataset_op, monkeypatch, user
):
    apply_operations(canvas, [pending_dataset_op])
    model = SemanticModel.objects.get(pk=canvas.semantic_model_id)
    model.metadata = {"last_build": {"status": "deferred"}}
    model.save(update_fields=["metadata", "updated_at"])
    assert canvas_projection(canvas)["can_commit"] is True
    assert canvas_service.infer_custom_dataset_columns.call_count == 1

    original = canvas_commit_module._commit_transaction

    def record_build_before_commit(canvas, pending, user):
        model.save(update_fields=["metadata", "updated_at"])
        return original(canvas, pending, user)

    monkeypatch.setattr(canvas_commit_module, "_commit_transaction", record_build_before_commit)
    monkeypatch.setattr(canvas_commit_module, "build_and_promote_cube_schema", Mock())
    assert commit_canvas(canvas, user)["blocked"] is False
    assert canvas_service.infer_custom_dataset_columns.call_count == 1


def test_canvas_commit_blocks_catalog_change_after_validation(
    canvas, workspace, pending_dataset_op, monkeypatch, user
):
    apply_operations(canvas, [pending_dataset_op])
    original = canvas_commit_module._commit_transaction

    def refresh_before_commit(canvas, pending, user):
        _refresh_canvas_catalog(workspace, monkeypatch, ["raw_users"])
        return original(canvas, pending, user)

    monkeypatch.setattr(canvas_commit_module, "_commit_transaction", refresh_before_commit)
    result = commit_canvas(canvas, user)
    assert result["blocked"] is True
    assert result["blocking_diagnostics"][0]["code"] == "CATALOG_CHANGED"
    assert result["blocking_diagnostics"][0]["object_uuid"] == ""
    assert not CustomDataset.objects.filter(workspace=workspace, name="visit_stats").exists()
    assert canvas.changes.get().change_type == SemanticCanvasChange.ChangeType.CREATE


@pytest.mark.django_db(transaction=True)
def test_canvas_commit_does_not_wait_for_a_catalog_refresh(
    canvas, pending_dataset_op, user, monkeypatch
):
    apply_operations(canvas, [pending_dataset_op])
    locked = Event()
    release = Event()
    monkeypatch.setattr(canvas_commit_module, "build_and_promote_cube_schema", Mock())

    def hold_catalog_lock():
        try:
            with transaction.atomic():
                SemanticModel.objects.select_for_update().get(pk=canvas.semantic_model_id)
                locked.set()
                assert release.wait(5)
        finally:
            connections["default"].close()

    with ThreadPoolExecutor(max_workers=1) as executor:
        holder = executor.submit(hold_catalog_lock)
        try:
            assert locked.wait(5)
            result = commit_canvas(canvas, user)
            assert result["blocked"] is True
            assert result["blocking_diagnostics"][0]["code"] == "CATALOG_CHANGED"
            assert canvas.changes.get().change_type == SemanticCanvasChange.ChangeType.CREATE
        finally:
            release.set()
        holder.result(timeout=5)


def test_canvas_commit_blocks_model_deactivation_after_validation(
    canvas, pending_dataset_op, user, monkeypatch
):
    apply_operations(canvas, [pending_dataset_op])
    original = canvas_commit_module._commit_transaction

    def deactivate_before_commit(canvas, pending, user):
        SemanticModel.objects.filter(pk=canvas.semantic_model_id).update(
            status=SemanticModel.Status.ERROR
        )
        return original(canvas, pending, user)

    monkeypatch.setattr(canvas_commit_module, "_commit_transaction", deactivate_before_commit)
    result = commit_canvas(canvas, user)
    assert result["blocked"] is True
    assert result["blocking_diagnostics"][0]["code"] == "CATALOG_CHANGED"


@pytest.mark.parametrize("object_type", ["dataset", "custom_dataset"])
@pytest.mark.parametrize("use_uuid", [False, True])
def test_pending_dataset_metadata_resolves_by_name_or_uuid(
    canvas, pending_dataset_op, object_type, use_uuid
):
    created = apply_operations(canvas, [pending_dataset_op])
    assert created["objects"][0]["fields"]["columns"] == [{"name": "username", "type": "text"}]
    assert created["pending_count"] == 1
    ref = str(canvas.changes.get().object_uuid) if use_uuid else "visit_stats"

    result = apply_operations(
        canvas,
        [{"op": "set", "target": f"{object_type}/{ref}/description", "value": "Distinct users"}],
    )

    assert "errors" not in result
    assert result["diagnostics"] == []
    assert canvas.changes.get().fields["description"] == "Distinct users"
    text = render_projection_text(canvas_projection(canvas), "graph")
    assert "Inferred output columns: username" in text
    assert "Output dimensions and count are generated on commit" in text


@pytest.mark.parametrize(
    "ambiguous_op",
    [
        {"op": "set", "target": "dataset/raw_visits/description", "value": "Ambiguous"},
        {"op": "delete_object", "object": "dataset/raw_visits"},
        {"op": "revert_object", "object": "dataset/raw_visits"},
        {"op": "remove_from_canvas", "object": "dataset/raw_visits"},
        {"op": "set", "target": "field/raw_visits.username/label", "value": "Ambiguous"},
        {
            "op": "create",
            "object_type": "field",
            "value": {
                "dataset": "raw_visits",
                "name": "distinct_users",
                "field_type": "measure",
                "measure_type": "count_distinct",
                "expression": "username",
            },
        },
    ],
)
def test_dataset_alias_rejects_saved_name_conflicting_with_draft_atomically(
    canvas, semantic_model, pending_dataset_op, ambiguous_op
):
    saved = _visits(semantic_model)
    apply_operations(
        canvas, [{"op": "set", "target": f"dataset/{saved.id}/description", "value": "Saved"}]
    )
    pending_dataset_op["value"]["name"] = saved.name
    staged = apply_operations(canvas, [pending_dataset_op])
    assert "DUPLICATE_DATASET_NAME" in {item["code"] for item in staged["diagnostics"]}
    before = dict(canvas.changes.values_list("object_uuid", "fields"))

    result = apply_operations(
        canvas,
        [
            {"op": "set", "target": f"dataset/{saved.id}/label", "value": "Must roll back"},
            ambiguous_op,
        ],
    )

    assert result["errors"][0]["code"] == "AMBIGUOUS_OBJECT"
    assert result["errors"][0]["op_index"] == 1
    assert "saved-dataset-uuid" in result["errors"][0]["message"]
    assert "draft-uuid" in result["errors"][0]["message"]
    assert dict(canvas.changes.values_list("object_uuid", "fields")) == before


@pytest.mark.parametrize("draft_type", ["dataset", "custom_dataset"])
def test_conflicting_dataset_name_can_be_targeted_by_explicit_uuid(
    canvas, semantic_model, pending_dataset_op, draft_type
):
    saved = _visits(semantic_model)
    pending_dataset_op["value"]["name"] = saved.name
    apply_operations(canvas, [pending_dataset_op])
    draft = canvas.changes.get()

    result = apply_operations(
        canvas,
        [
            {"op": "set", "target": f"dataset/{saved.id}/description", "value": "Saved dataset"},
            {
                "op": "set",
                "target": f"{draft_type}/{draft.object_uuid}/description",
                "value": "Pending dataset",
            },
        ],
    )

    assert "errors" not in result
    assert canvas.changes.get(object_uuid=saved.id).fields == {"description": "Saved dataset"}
    draft.refresh_from_db()
    assert draft.fields["description"] == "Pending dataset"
    assert draft.change_type == SemanticCanvasChange.ChangeType.CREATE


def test_duplicate_pending_dataset_names_require_explicit_draft_uuid(canvas, pending_dataset_op):
    apply_operations(canvas, [pending_dataset_op, pending_dataset_op])
    before = dict(canvas.changes.values_list("object_uuid", "fields"))

    result = apply_operations(
        canvas,
        [{"op": "set", "target": "custom_dataset/visit_stats/label", "value": "Ambiguous"}],
    )

    assert result["errors"][0]["code"] == "AMBIGUOUS_OBJECT"
    assert dict(canvas.changes.values_list("object_uuid", "fields")) == before


@pytest.mark.parametrize(
    "field_op",
    [
        {"op": "set", "target": "field/visit_stats.username/description", "value": "User"},
        {
            "op": "create",
            "object_type": "field",
            "value": {
                "dataset": "visit_stats",
                "name": "distinct_users",
                "field_type": "measure",
                "measure_type": "count_distinct",
                "expression": "username",
            },
        },
    ],
)
@pytest.mark.parametrize("same_batch", [False, True])
def test_pending_dataset_field_error_explains_safe_next_step(
    canvas, pending_dataset_op, field_op, same_batch
):
    if not same_batch:
        apply_operations(canvas, [pending_dataset_op])
    result = apply_operations(canvas, [pending_dataset_op, field_op] if same_batch else [field_op])

    error = result["errors"][0]
    assert error["code"] == "DATASET_NOT_COMMITTED"
    assert error["op_index"] == int(same_batch)
    assert "This atomic batch was not applied" in error["message"]
    assert "Otherwise keep the existing draft" in error["message"]
    assert "Commit only if authorized" in error["message"]
    assert canvas.changes.count() == (0 if same_batch else 1)
    assert not canvas.semantic_model.datasets.filter(name="visit_stats").exists()


def test_custom_dataset_create_commit_then_curate_generated_fields(
    canvas, pending_dataset_op, semantic_model, workspace, user, monkeypatch
):
    cube_schema = CubeSchema(workspace=workspace, semantic_model=semantic_model, content_hash="ok")
    promote = Mock(return_value=cube_schema)
    monkeypatch.setattr(canvas_commit_module, "build_and_promote_cube_schema", promote)

    staged = apply_operations(
        canvas,
        [
            pending_dataset_op,
            {"op": "set", "target": "dataset/visit_stats/description", "value": "Distinct users"},
        ],
        user,
    )
    assert staged["can_commit"] is True
    first_commit = commit_canvas(canvas, user)
    assert first_commit["committed"]
    assert first_commit["cube_schema"] == {"ok": True, "content_hash": "ok"}
    dataset = semantic_model.datasets.get(name="visit_stats")
    assert dataset.fields.get(name="username").expression == "username"
    assert dataset.fields.get(name="count").measure_type == "count"

    curated = apply_operations(
        canvas,
        [
            {"op": "set", "target": "field/visit_stats.username/description", "value": "User"},
            {"op": "set", "target": "field/visit_stats.count/label", "value": "Users"},
        ],
        user,
    )
    assert curated["can_commit"] is True
    assert curated["diagnostics"] == []
    assert curated["pending_count"] == 2
    second_commit = commit_canvas(canvas, user)
    assert len(second_commit["committed"]) == 2
    assert second_commit["cube_schema"]["ok"] is True
    assert canvas_projection(canvas)["pending_count"] == 0
    assert dataset.fields.get(name="username").description == "User"
    assert CustomDataset.objects.filter(workspace=workspace, name="visit_stats").count() == 1
    assert promote.call_count == 2
    promote.assert_called_with(workspace, model=semantic_model)


@pytest.mark.asyncio
@pytest.mark.django_db(transaction=True)
async def test_canvas_apply_tool_exposes_inferred_columns_and_pending_count(
    canvas, pending_dataset_op, workspace, user
):
    tools = {
        item.name: item for item in create_canvas_tools(workspace, user, str(canvas.thread_id))
    }

    result = await tools["canvas_apply"].ainvoke({"operations": [pending_dataset_op]})

    assert result["pending_count"] == 1
    assert "Inferred output columns: username" in result["text"]
    assert result["can_commit"] is True


@pytest.mark.asyncio
@pytest.mark.django_db(transaction=True)
@pytest.mark.parametrize("operation", ["add_existing", "revert_object"])
async def test_canvas_manager_reports_clean_canvas_only_operations_as_completed(
    canvas, workspace, user, monkeypatch, operation
):
    tools = {
        item.name: item for item in create_canvas_tools(workspace, user, str(canvas.thread_id))
    }
    if operation == "revert_object":
        await tools["canvas_apply"].ainvoke(
            {
                "operations": [
                    {"op": "set", "target": "dataset/raw_visits/description", "value": "Pending"}
                ]
            }
        )
        operations = [{"op": "revert_object", "object": "dataset/raw_visits"}]
    else:
        operations = [{"op": "add_existing", "object_type": "dataset", "ref": "raw_visits"}]
    report = await tools["canvas_apply"].ainvoke({"operations": operations})
    assert report["pending_count"] == 0
    assert report["can_commit"] is False
    assert report["diagnostics"] == []

    class CleanGraph:
        async def astream_events(self, *_args, **_kwargs):
            yield {
                "event": "on_tool_end",
                "name": "canvas_apply",
                "run_id": "apply-clean",
                "data": {
                    "output": ToolMessage(
                        name="canvas_apply", tool_call_id="apply-clean", content=json.dumps(report)
                    )
                },
            }
            yield {
                "event": "on_chain_end",
                "name": "agent",
                "data": {
                    "output": {
                        "messages": [
                            AIMessage(content=json.dumps({"status": "done", "message": "Done."}))
                        ]
                    }
                },
            }

    monkeypatch.setattr(
        "apps.agents.tools.canvas_manager_agent._build_canvas_manager_graph",
        lambda *_args: CleanGraph(),
    )
    queue = asyncio.Queue()
    manager = create_canvas_manager_tool(workspace, user, [], str(canvas.thread_id))

    result = await manager.ainvoke({"task": operation, "subagent_event_queue": queue})

    assert result["status"] == "done"
    assert result["pending_count"] == 0
    assert result["committed"] is False
    assert result["diagnostics"] == []
    assert result["message"] == "Done."
    events = [queue.get_nowait()["event"] for _ in range(queue.qsize())]
    assert events[-1]["data"]["phase"] == "completed"
    assert result["subagent_trace"]["events"][0]["data"]["phase"] == "completed"


def test_custom_dataset_fields_can_be_deleted_and_stay_hidden(
    canvas, semantic_model, monkeypatch, user
):
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "visit_stats",
                    "primary_key": "username",
                    "definition_sql": "select username, count(*) as visit_count from raw_visits group by username",
                },
            }
        ],
        user,
    )
    assert commit_canvas(canvas, user)["blocked"] is False

    dataset = semantic_model.datasets.get(name="visit_stats")
    assert dataset.fields.filter(name="visit_count", is_visible=True).exists()
    assert dataset.fields.filter(name="sum_visit_count", is_visible=True).exists()

    result = apply_operations(
        canvas,
        [
            {"op": "delete_object", "object": "field/visit_stats.visit_count"},
            {"op": "delete_object", "object": "field/visit_stats.sum_visit_count"},
        ],
        user,
    )

    assert "errors" not in result
    report = commit_canvas(canvas, user)
    assert report["blocked"] is False

    hidden_dimension = dataset.fields.get(name="visit_count")
    hidden_measure = dataset.fields.get(name="sum_visit_count")
    assert hidden_dimension.is_visible is False
    assert hidden_measure.is_visible is False
    assert "is_visible" in hidden_dimension.metadata["curated_fields"]
    assert "is_visible" in hidden_measure.metadata["curated_fields"]

    catalog_service._sync_fields(
        dataset,
        [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
        None,
    )
    hidden_dimension.refresh_from_db()
    hidden_measure.refresh_from_db()
    assert hidden_dimension.is_visible is False
    assert hidden_measure.is_visible is False


def test_custom_dataset_requires_primary_key(canvas, monkeypatch, user):
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "no_pk_stats",
                    "definition_sql": "select username, count(*) as visit_count from raw_visits group by username",
                },
            }
        ],
        user,
    )

    codes = {d["code"] for d in result["diagnostics"]}
    assert "MISSING_PRIMARY_KEY" in codes
    assert commit_canvas(canvas, user)["blocked"] is True

    # An `id` output column is accepted as the default primary key.
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [{"name": "id", "type": "bigint"}],
    )
    apply_operations(
        canvas, [{"op": "revert_object", "object": "custom_dataset/no_pk_stats"}], user
    )
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "id_stats",
                    "definition_sql": "select visit_id as id from raw_visits",
                },
            }
        ],
        user,
    )
    assert result["diagnostics"] == []


def test_primary_key_editable_on_custom_datasets_only(
    canvas, semantic_model, workspace, monkeypatch, user
):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    monkeypatch.setattr(
        canvas_service,
        "infer_custom_dataset_columns",
        lambda _workspace, _sql: [
            {"name": "username", "type": "text"},
            {"name": "visit_count", "type": "bigint"},
        ],
    )
    apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {
                    "name": "pk_stats",
                    "primary_key": "username",
                    "definition_sql": "select username, count(*) as visit_count from raw_visits group by username",
                },
            }
        ],
        user,
    )
    commit_canvas(canvas, user)

    changed = apply_operations(
        canvas,
        [{"op": "set", "target": "dataset/pk_stats/primary_key", "value": "visit_count"}],
        user,
    )
    assert "errors" not in changed
    commit_canvas(canvas, user)
    assert semantic_model.datasets.get(name="pk_stats").primary_key == "visit_count"

    unknown = apply_operations(
        canvas, [{"op": "set", "target": "dataset/pk_stats/primary_key", "value": "nope"}], user
    )
    assert unknown["errors"][0]["code"] == "UNKNOWN_COLUMN"

    physical = apply_operations(
        canvas,
        [{"op": "set", "target": "dataset/raw_visits/primary_key", "value": "username"}],
        user,
    )
    assert physical["errors"][0]["code"] == "INVALID_TARGET"


def test_fallback_primary_key_for_base_tables_only():
    columns = [{"name": "id", "type": "bigint"}, {"name": "value", "type": "text"}]
    assert catalog_service._fallback_primary_key("table", columns) == "id"
    assert catalog_service._fallback_primary_key("view", columns) == ""
    assert catalog_service._fallback_primary_key("table", [{"name": "value"}]) == ""


def test_invalid_custom_sql_blocks_commit(canvas, user):
    result = apply_operations(
        canvas,
        [
            {
                "op": "create",
                "object_type": "custom_dataset",
                "value": {"name": "bad_stats", "definition_sql": "drop table raw_visits"},
            }
        ],
        user,
    )
    codes = {d["code"] for d in result["diagnostics"]}
    assert "INVALID_SQL" in codes
    report = commit_canvas(canvas, user)
    assert report["blocked"] is True


def test_conflict_detected_when_base_moves(canvas, semantic_model, user):
    apply_operations(
        canvas,
        [{"op": "set", "target": "dataset/raw_visits/description", "value": "draft"}],
        user,
    )
    visits = _visits(semantic_model)
    visits.label = "Visits (renamed elsewhere)"
    visits.save()

    projection = canvas_projection(canvas)
    assert projection["objects"][0]["state"] == "conflict"
    report = commit_canvas(canvas, user)
    assert report["committed"] == []
    assert report["conflicts"]

    # revert_object picks up the current persisted version again.
    apply_operations(canvas, [{"op": "revert_object", "object": "dataset/raw_visits"}], user)
    assert canvas_projection(canvas)["objects"][0]["state"] == "unchanged"


def test_refresh_preserves_curated_and_canvas_fields(
    canvas, semantic_model, workspace, monkeypatch, user
):
    monkeypatch.setattr(
        canvas_commit_module, "build_and_promote_cube_schema", lambda ws, model: None
    )
    apply_operations(
        canvas,
        [
            {"op": "set", "target": "dataset/raw_visits/label", "value": "Curated Visits"},
            {
                "op": "create",
                "object_type": "field",
                "value": {
                    "dataset": "raw_visits",
                    "name": "total_amount",
                    "field_type": "measure",
                    "measure_type": "sum",
                    "expression": "amount",
                },
            },
        ],
        user,
    )
    commit_canvas(canvas, user)

    monkeypatch.setattr(
        catalog_service,
        "load_physical_tables",
        lambda _workspace: (
            "tenant_schema",
            [
                PhysicalTable(
                    name="raw_visits",
                    type="table",
                    description="Visits",
                    columns=[
                        {"name": "visit_id", "type": "bigint"},
                        {"name": "username", "type": "text"},
                        {"name": "amount", "type": "numeric"},
                    ],
                    primary_key="visit_id",
                ),
            ],
        ),
    )
    monkeypatch.setattr(catalog_service, "get_registry", lambda: _empty_registry())

    catalog_service.ensure_semantic_model(workspace)

    visits = workspace.semantic_datasets.get(name="raw_visits")
    assert visits.label == "Curated Visits"
    assert "label" in visits.metadata["curated_fields"]
    canvas_field = visits.fields.get(name="total_amount")
    assert canvas_field.is_visible is True
    assert canvas_field.metadata["source"] == "canvas"


def _empty_registry():
    class _Registry:
        def list(self):
            return []

    return _Registry()


def test_can_write_canvas_matches_rest_policy(workspace, user, read_user):
    from apps.agents.tools.canvas_tool import can_write_canvas

    assert can_write_canvas(workspace, user) is True
    assert can_write_canvas(workspace, read_user) is False
    assert can_write_canvas(workspace, None) is False


@pytest.mark.asyncio
@pytest.mark.django_db(transaction=True)
async def test_canvas_write_tools_forbidden_for_read_role(workspace, read_user, semantic_model):
    from apps.agents.tools.canvas_tool import create_canvas_tools

    thread = await Thread.objects.acreate(workspace=workspace, user=read_user)
    tools = {t.name: t for t in create_canvas_tools(workspace, read_user, str(thread.id))}

    apply_result = await tools["canvas_apply"].ainvoke(
        {"operations": [{"op": "add_existing", "object_type": "dataset", "ref": "raw_visits"}]}
    )
    assert apply_result["errors"][0]["code"] == "FORBIDDEN"

    commit_result = await tools["canvas_commit"].ainvoke({})
    assert commit_result["errors"][0]["code"] == "FORBIDDEN"

    assert await SemanticCanvasChange.objects.acount() == 0
    # Reads stay available to read-only members, matching the REST policy.
    read_result = await tools["canvas_read"].ainvoke({"selector": "graph"})
    assert "Canvas is empty" in read_result


@pytest.mark.asyncio
@pytest.mark.django_db(transaction=True)
async def test_canvas_read_rechecks_removed_membership_before_thread_lookup(workspace, read_user):
    from apps.agents.tools.canvas_tool import create_canvas_read_tool

    conversation_id = str(uuid.uuid4())
    tool = create_canvas_read_tool(workspace, read_user, conversation_id)
    await read_user.workspace_memberships.filter(workspace=workspace).adelete()

    result = await tool.ainvoke({"selector": "graph"})

    assert "access denied" in result.lower()
    assert not await Thread.objects.filter(id=conversation_id).aexists()


@pytest.mark.django_db
def test_build_tools_gates_canvas_manager_on_write_role(workspace, user):
    from apps.agents.graph.base import _build_tools

    writable = {
        t.name
        for t in _build_tools(
            workspace, user, [], conversation_id="t1", interactive=True, canvas_write=True
        )
    }
    assert {"canvas_read", "canvas_manager"} <= writable

    readonly = {
        t.name
        for t in _build_tools(
            workspace, user, [], conversation_id="t1", interactive=True, canvas_write=False
        )
    }
    assert "canvas_read" in readonly
    assert "canvas_manager" not in readonly


@pytest.mark.django_db
def test_thread_canvas_api_flow(client, workspace, user, semantic_model):
    client.force_login(user)
    thread = Thread.objects.create(workspace=workspace, user=user)
    base = f"/api/workspaces/{workspace.id}/threads/{thread.id}/canvas/"

    projection = client.get(base).json()
    assert projection["objects"] == []
    assert projection["can_commit"] is False

    response = client.post(
        f"{base}apply/",
        {
            "operations": [
                {"op": "set", "target": "dataset/raw_visits/description", "value": "All visits"}
            ]
        },
        content_type="application/json",
    )
    assert response.status_code == 200
    assert response.json()["objects"][0]["state"] == "edited"

    bad = client.post(
        f"{base}apply/",
        {"operations": [{"op": "set", "target": "dataset/raw_visits/nope", "value": "x"}]},
        content_type="application/json",
    )
    assert bad.status_code == 400
    assert bad.json()["errors"][0]["code"] == "INVALID_TARGET"


@pytest.mark.django_db
def test_thread_canvas_api_requires_write_role(client, workspace, read_user, semantic_model):
    client.force_login(read_user)
    thread = Thread.objects.create(workspace=workspace, user=read_user)
    base = f"/api/workspaces/{workspace.id}/threads/{thread.id}/canvas/"

    assert client.get(base).status_code == 200
    response = client.post(f"{base}apply/", {"operations": []}, content_type="application/json")
    assert response.status_code == 403


@pytest.mark.django_db
def test_thread_canvas_api_rejects_foreign_thread(
    client, workspace, user, read_user, semantic_model
):
    client.force_login(user)
    foreign = Thread.objects.create(workspace=workspace, user=read_user)
    response = client.get(f"/api/workspaces/{workspace.id}/threads/{foreign.id}/canvas/")
    assert response.status_code == 404
