"""Semantic model source-of-truth objects for Scout."""

from __future__ import annotations

import uuid

from django.conf import settings
from django.db import models


class SemanticModel(models.Model):
    """Workspace-level semantic model that can be compiled to Cube later."""

    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        DRAFT = "draft", "Draft"
        ERROR = "error", "Error"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.OneToOneField(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_model",
    )
    name = models.CharField(max_length=255)
    version = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)
    diagnostics = models.JSONField(default=list, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["workspace__name"]

    def __str__(self) -> str:
        return f"{self.workspace}: semantic model v{self.version}"


class SemanticDataset(models.Model):
    """Business-facing dataset exposed to the agent and dataset browser."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    semantic_model = models.ForeignKey(
        SemanticModel,
        on_delete=models.CASCADE,
        related_name="datasets",
    )
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_datasets",
    )
    name = models.SlugField(max_length=255)
    label = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    schema_name = models.CharField(max_length=255, blank=True)
    table_name = models.CharField(max_length=255)
    primary_key = models.CharField(max_length=255, blank=True)
    row_count = models.BigIntegerField(null=True, blank=True)
    is_visible = models.BooleanField(default=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["workspace", "name"],
                name="unique_semantic_dataset_name_per_workspace",
            )
        ]
        indexes = [
            models.Index(fields=["workspace", "is_visible"]),
        ]

    def __str__(self) -> str:
        return self.label or self.name


class SemanticField(models.Model):
    """Dimension, time dimension, or measure on a semantic dataset."""

    class FieldType(models.TextChoices):
        DIMENSION = "dimension", "Dimension"
        TIME_DIMENSION = "time_dimension", "Time dimension"
        MEASURE = "measure", "Measure"

    class MeasureType(models.TextChoices):
        COUNT = "count", "Count"
        SUM = "sum", "Sum"
        AVG = "avg", "Average"
        MIN = "min", "Minimum"
        MAX = "max", "Maximum"
        NUMBER = "number", "Number"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dataset = models.ForeignKey(
        SemanticDataset,
        on_delete=models.CASCADE,
        related_name="fields",
    )
    name = models.SlugField(max_length=255)
    label = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    field_type = models.CharField(max_length=30, choices=FieldType.choices)
    data_type = models.CharField(max_length=100, blank=True)
    expression = models.CharField(
        max_length=500,
        help_text="Trusted column name or expression generated by Scout.",
    )
    measure_type = models.CharField(max_length=20, choices=MeasureType.choices, blank=True)
    is_visible = models.BooleanField(default=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["field_type", "name"]
        constraints = [
            models.UniqueConstraint(
                fields=["dataset", "name"],
                name="unique_semantic_field_name_per_dataset",
            )
        ]
        indexes = [
            models.Index(fields=["dataset", "field_type", "is_visible"]),
        ]

    def __str__(self) -> str:
        return self.member_name

    @property
    def member_name(self) -> str:
        return f"{self.dataset.name}.{self.name}"


class SemanticRelationship(models.Model):
    """Relationship between two semantic datasets."""

    class RelationshipType(models.TextChoices):
        ONE_TO_ONE = "one_to_one", "One to one"
        ONE_TO_MANY = "one_to_many", "One to many"
        MANY_TO_ONE = "many_to_one", "Many to one"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_relationships",
    )
    name = models.SlugField(max_length=255)
    from_dataset = models.ForeignKey(
        SemanticDataset,
        on_delete=models.CASCADE,
        related_name="outgoing_relationships",
    )
    to_dataset = models.ForeignKey(
        SemanticDataset,
        on_delete=models.CASCADE,
        related_name="incoming_relationships",
    )
    relationship_type = models.CharField(
        max_length=30,
        choices=RelationshipType.choices,
        default=RelationshipType.MANY_TO_ONE,
    )
    join_expression = models.TextField(blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["workspace", "name"],
                name="unique_semantic_relationship_name_per_workspace",
            )
        ]

    def __str__(self) -> str:
        return self.name


class SemanticCanvas(models.Model):
    """Lightweight draft canvas for semantic-model changes."""

    class Status(models.TextChoices):
        OPEN = "open", "Open"
        COMMITTED = "committed", "Committed"
        DISCARDED = "discarded", "Discarded"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_canvases",
    )
    semantic_model = models.ForeignKey(
        SemanticModel,
        on_delete=models.CASCADE,
        related_name="canvases",
    )
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.OPEN)
    changes = models.JSONField(default=dict, blank=True)
    diagnostics = models.JSONField(default=list, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="semantic_canvases",
    )
    committed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]
        indexes = [
            models.Index(fields=["workspace", "status"]),
        ]

    def __str__(self) -> str:
        return f"{self.workspace} canvas {self.id}"
