"""Semantic model source-of-truth objects for Scout."""

from __future__ import annotations

import uuid

from django.conf import settings
from django.db import models
from django.db.models import Q


class SemanticModel(models.Model):
    """Workspace-level semantic model that can be compiled to Cube later."""

    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        DRAFT = "draft", "Draft"
        ERROR = "error", "Error"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.OneToOneField(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_model",
    )
    name = models.CharField(max_length=255)
    version = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)
    diagnostics = models.JSONField(default=list, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["workspace__name"]

    def __str__(self) -> str:
        return f"{self.workspace}: semantic model v{self.version}"


class SemanticDataset(models.Model):
    """Business-facing dataset exposed to the agent and dataset browser."""

    class SourceKind(models.TextChoices):
        PHYSICAL = "physical", "Physical"
        CUSTOM = "custom", "Custom"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    semantic_model = models.ForeignKey(
        SemanticModel,
        on_delete=models.CASCADE,
        related_name="datasets",
    )
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_datasets",
    )
    name = models.SlugField(max_length=255)
    label = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    source_kind = models.CharField(
        max_length=20,
        choices=SourceKind.choices,
        default=SourceKind.PHYSICAL,
    )
    custom_dataset = models.OneToOneField(
        "semantic.CustomDataset",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="semantic_dataset",
    )
    schema_name = models.CharField(max_length=255, blank=True)
    table_name = models.CharField(max_length=255)
    primary_key = models.CharField(max_length=255, blank=True)
    row_count = models.BigIntegerField(null=True, blank=True)
    is_visible = models.BooleanField(default=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["workspace", "name"],
                name="unique_semantic_dataset_name_per_workspace",
            )
        ]
        indexes = [
            models.Index(fields=["workspace", "is_visible"]),
            models.Index(fields=["workspace", "source_kind", "is_visible"]),
        ]

    def __str__(self) -> str:
        return self.label or self.name


class SemanticField(models.Model):
    """Dimension, time dimension, or measure on a semantic dataset."""

    class FieldType(models.TextChoices):
        DIMENSION = "dimension", "Dimension"
        TIME_DIMENSION = "time_dimension", "Time dimension"
        MEASURE = "measure", "Measure"

    class MeasureType(models.TextChoices):
        COUNT = "count", "Count"
        SUM = "sum", "Sum"
        AVG = "avg", "Average"
        MIN = "min", "Minimum"
        MAX = "max", "Maximum"
        NUMBER = "number", "Number"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dataset = models.ForeignKey(
        SemanticDataset,
        on_delete=models.CASCADE,
        related_name="fields",
    )
    name = models.SlugField(max_length=255)
    label = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    field_type = models.CharField(max_length=30, choices=FieldType.choices)
    data_type = models.CharField(max_length=100, blank=True)
    expression = models.CharField(
        max_length=500,
        help_text="Trusted column name or expression generated by Scout.",
    )
    measure_type = models.CharField(max_length=20, choices=MeasureType.choices, blank=True)
    is_visible = models.BooleanField(default=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["field_type", "name"]
        constraints = [
            models.UniqueConstraint(
                fields=["dataset", "name"],
                name="unique_semantic_field_name_per_dataset",
            )
        ]
        indexes = [
            models.Index(fields=["dataset", "field_type", "is_visible"]),
        ]

    def __str__(self) -> str:
        return self.member_name

    @property
    def member_name(self) -> str:
        return f"{self.dataset.name}.{self.name}"


class SemanticRelationship(models.Model):
    """Relationship between two semantic datasets."""

    class RelationshipType(models.TextChoices):
        ONE_TO_ONE = "one_to_one", "One to one"
        ONE_TO_MANY = "one_to_many", "One to many"
        MANY_TO_ONE = "many_to_one", "Many to one"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_relationships",
    )
    name = models.SlugField(max_length=255)
    from_dataset = models.ForeignKey(
        SemanticDataset,
        on_delete=models.CASCADE,
        related_name="outgoing_relationships",
    )
    to_dataset = models.ForeignKey(
        SemanticDataset,
        on_delete=models.CASCADE,
        related_name="incoming_relationships",
    )
    relationship_type = models.CharField(
        max_length=30,
        choices=RelationshipType.choices,
        default=RelationshipType.MANY_TO_ONE,
    )
    join_expression = models.TextField(blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["workspace", "name"],
                name="unique_semantic_relationship_name_per_workspace",
            )
        ]

    def __str__(self) -> str:
        return self.name


class CustomDataset(models.Model):
    """Workspace-authored dataset definition compiled into the semantic model."""

    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        DRAFT = "draft", "Draft"
        ERROR = "error", "Error"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="custom_datasets",
    )
    name = models.SlugField(max_length=255)
    label = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    definition_sql = models.TextField(blank=True)
    definition_json = models.JSONField(default=dict, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)
    diagnostics = models.JSONField(default=list, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="custom_datasets",
    )
    is_visible = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["workspace", "name"],
                name="unique_custom_dataset_name_per_workspace",
            )
        ]
        indexes = [
            models.Index(fields=["workspace", "status", "is_visible"]),
        ]

    def __str__(self) -> str:
        return self.label or self.name


class CubeSchema(models.Model):
    """Active Cube YAML generated from a workspace semantic model."""

    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        DRAFT = "draft", "Draft"
        ERROR = "error", "Error"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="cube_schemas",
    )
    semantic_model = models.ForeignKey(
        SemanticModel,
        on_delete=models.CASCADE,
        related_name="cube_schemas",
    )
    filename = models.CharField(max_length=255)
    content = models.TextField()
    content_hash = models.CharField(max_length=64, db_index=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)
    diagnostics = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["workspace__name", "filename"]
        constraints = [
            models.UniqueConstraint(
                fields=["workspace", "filename"],
                name="unique_cube_schema_filename_per_workspace",
            ),
            models.UniqueConstraint(
                fields=["workspace", "semantic_model"],
                condition=Q(status="active"),
                name="unique_active_cube_schema_per_model",
            ),
        ]
        indexes = [
            models.Index(fields=["workspace", "status"]),
            models.Index(fields=["semantic_model", "status"]),
        ]

    def __str__(self) -> str:
        return f"{self.workspace}: {self.filename}"


class SemanticCanvas(models.Model):
    """Thread-bound changeset over the workspace's persisted semantic model.

    The canvas stores no object copies — only membership and pending deltas
    (see SemanticCanvasChange). Rendered objects, diffs, and validation state
    are derived on read by overlaying deltas onto the persisted rows.
    """

    class Status(models.TextChoices):
        OPEN = "open", "Open"
        DISCARDED = "discarded", "Discarded"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    thread = models.OneToOneField(
        "chat.Thread",
        on_delete=models.CASCADE,
        related_name="semantic_canvas",
    )
    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="semantic_canvases",
    )
    semantic_model = models.ForeignKey(
        SemanticModel,
        on_delete=models.CASCADE,
        related_name="canvases",
    )
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.OPEN)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="semantic_canvases",
    )
    committed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]
        indexes = [
            models.Index(fields=["workspace", "status"]),
        ]

    def __str__(self) -> str:
        return f"{self.workspace} canvas {self.id}"


class SemanticCanvasChange(models.Model):
    """One row per (canvas, object): membership plus the pending delta.

    Derived states (never stored): create -> "new"; update with empty fields
    -> "unchanged" (membership row); update with a delta -> "edited"; delete
    -> "deleted"; a pending update/delete whose base_fingerprint no longer
    matches the persisted row's updated_at -> "conflict".
    """

    class ObjectType(models.TextChoices):
        DATASET = "dataset", "Dataset"
        FIELD = "field", "Field"
        RELATIONSHIP = "relationship", "Relationship"
        CUSTOM_DATASET = "custom_dataset", "Custom dataset"

    class ChangeType(models.TextChoices):
        CREATE = "create", "Create"
        UPDATE = "update", "Update"
        DELETE = "delete", "Delete"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    canvas = models.ForeignKey(
        SemanticCanvas,
        on_delete=models.CASCADE,
        related_name="changes",
    )
    object_type = models.CharField(max_length=30, choices=ObjectType.choices)
    object_uuid = models.UUIDField()
    change_type = models.CharField(max_length=20, choices=ChangeType.choices)
    fields = models.JSONField(default=dict, blank=True)
    base_fingerprint = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["canvas", "object_uuid"],
                name="one_canvas_change_per_object",
            )
        ]
        indexes = [
            models.Index(fields=["canvas", "object_type"]),
        ]

    def __str__(self) -> str:
        return f"{self.change_type} {self.object_type}/{self.object_uuid}"
