# Generated by Django 6.0.2 on 2026-02-10 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_remove_savedquery_and_conversationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'Production Analytics DB'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('db_host', models.CharField(max_length=255)),
                ('db_port', models.IntegerField(default=5432)),
                ('db_name', models.CharField(max_length=255)),
                ('_db_user', models.BinaryField(db_column='db_user')),
                ('_db_password', models.BinaryField(db_column='db_password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('manage_database_connections', 'Can create and edit database connections')],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'CommCare Production'", max_length=255)),
                ('source_type', models.CharField(choices=[('commcare', 'CommCare'), ('commcare_connect', 'CommCare Connect')], max_length=50)),
                ('base_url', models.URLField(help_text="Base API URL, e.g. 'https://www.commcarehq.org'")),
                ('config', models.JSONField(blank=True, default=dict)),
                ('oauth_client_id', models.CharField(blank=True, max_length=255)),
                ('_oauth_client_secret', models.BinaryField(blank=True, db_column='oauth_client_secret', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_mode', models.CharField(choices=[('project', 'Project-level'), ('user', 'User-level')], default='user', max_length=20)),
                ('sync_config', models.JSONField(blank=True, default=dict)),
                ('refresh_interval_hours', models.IntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='datasources.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_data_sources', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Data Source',
                'verbose_name_plural': 'Project Data Sources',
                'unique_together': {('project', 'data_source')},
            },
        ),
        migrations.CreateModel(
            name='MaterializedDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(help_text='PostgreSQL schema name (max 63 chars)', max_length=63)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('ready', 'Ready'), ('error', 'Error'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('row_counts', models.JSONField(blank=True, default=dict, help_text='Row counts per table, e.g. {"forms": 1500, "cases": 300}')),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('sync_cursor', models.JSONField(blank=True, default=dict, help_text='Cursor for resuming interrupted syncs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialized_datasets', to=settings.AUTH_USER_MODEL)),
                ('project_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_datasets', to='datasources.projectdatasource')),
            ],
            options={
                'verbose_name': 'Materialized Dataset',
                'verbose_name_plural': 'Materialized Datasets',
                'unique_together': {('project_data_source', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.JSONField(blank=True, default=dict, help_text='Progress per dataset, e.g. {"forms": {"fetched": 500, "total": 1500}}')),
                ('resume_after', models.DateTimeField(blank=True, help_text='When to resume after rate limiting', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materialized_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='datasources.materializeddataset')),
            ],
            options={
                'verbose_name': 'Sync Job',
                'verbose_name_plural': 'Sync Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_access_token', models.BinaryField(db_column='access_token')),
                ('_refresh_token', models.BinaryField(db_column='refresh_token')),
                ('token_expires_at', models.DateTimeField()),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('external_user_id', models.CharField(blank=True, help_text='User ID in the external system', max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='datasources.datasource')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_source_credentials', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_source_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source Credential',
                'verbose_name_plural': 'Data Source Credentials',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('user__isnull', True)), models.Q(('project__isnull', True), ('user__isnull', False)), _connector='OR'), name='credential_project_xor_user')],
            },
        ),
    ]
