# Generated by Django 5.2.11 on 2026-10-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memory", "0001_personal_memory"),
        ("workspaces", "0021_workspaceloadtiming"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceMemoryEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("memory_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("chat", "Chat"), ("memory_page", "Memory page")], max_length=16
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The memory's text after the change, or as deleted."
                    ),
                ),
                ("previous_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_events",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"], name="memory_work_workspa_11f598_idx"
                    )
                ],
            },
        ),
    ]
