# Generated by Django 5.2.11 on 2026-06-18 20:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_initial"),
        ("workspaces", "0005_add_view_schema_last_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelGapSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="The user's original question that triggered the fallback."
                    ),
                ),
                (
                    "sql",
                    models.TextField(
                        blank=True,
                        help_text="The raw SQL the agent used when falling back from the semantic layer.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_gap_signals",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"], name="knowledge_m_workspa_9f3ef5_idx"
                    )
                ],
            },
        ),
    ]
