# Generated by Django 5.2.11 on 2026-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_rekey_table_knowledge_to_logical_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlearning',
            name='corrected_sql',
            field=models.TextField(blank=True, help_text='Disabled legacy field retained for old learning records.'),
        ),
        migrations.AlterField(
            model_name='agentlearning',
            name='original_sql',
            field=models.TextField(blank=True, help_text='Disabled legacy field retained for old learning records.'),
        ),
    ]
