# Generated by Django 5.2.11 on 2026-10-06 14:17

from django.db import migrations, models
from django.db.models import F


def backfill_updated_at(apps, schema_editor):
    apps.get_model("knowledge", "AgentLearning").objects.update(updated_at=F("created_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0004_alter_agentlearning_corrected_sql_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlearning",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="agentlearning",
            name="applies_to_tables",
            field=models.JSONField(
                blank=True, default=list, help_text="Tables this memory applies to, if any."
            ),
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
    ]
