# Generated by Django 5.2.11 on 2026-10-06 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_agentlearning_updated_at"),
        ("workspaces", "0021_workspaceloadtiming"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agentlearning",
            index=models.Index(
                fields=["workspace", "is_active", "-created_at"],
                name="knowledge_a_workspa_ba638c_idx",
            ),
        ),
    ]
