# Generated by Django 5.2.11 on 2026-03-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0006_rescope_to_workspace"),
        ("projects", "0019_migrate_tenant_workspaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentlearning",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learnings",
                to="projects.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeentry",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_entries",
                to="projects.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="tableknowledge",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_knowledge",
                to="projects.workspace",
            ),
        ),
    ]
