# Generated by Django 5.2.11 on 2026-03-04 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0007_add_custom_workspace_fk"),
        ("workspace", "0017_add_custom_workspace_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tableknowledge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "table_name"),
                name="unique_table_knowledge_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="tableknowledge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_workspace__isnull", False)),
                fields=("custom_workspace", "table_name"),
                name="unique_table_knowledge_per_custom_workspace",
            ),
        ),
    ]
