# Generated by Django 5.2.11 on 2026-02-20 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tenantmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('oauth', 'OAuth Token'), ('api_key', 'API Key')], max_length=20)),
                ('encrypted_credential', models.CharField(blank=True, help_text='Fernet-encrypted opaque string. Empty for OAuth type.', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='users.tenantmembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
