# Generated by Django 5.2.11 on 2026-03-04 11:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_tenantcredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("commcare", "CommCare HQ"),
                            ("commcare_connect", "CommCare Connect"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Provider-assigned identifier (CommCare domain name or Connect org ID).",
                        max_length=255,
                    ),
                ),
                ("canonical_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["canonical_name"],
                "unique_together": {("provider", "external_id")},
            },
        ),
    ]
