# Generated by Django 5.2.11 on 2026-06-05 15:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_add_ocs_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmembership",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="team_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="team_slug",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="TenantConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("commcare", "CommCare HQ"),
                            ("commcare_connect", "CommCare Connect"),
                            ("ocs", "Open Chat Studio"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[("oauth", "OAuth Token"), ("api_key", "API Key")], max_length=20
                    ),
                ),
                (
                    "encrypted_credential",
                    models.CharField(
                        blank=True,
                        help_text="Fernet-encrypted opaque string. Empty for OAuth (token lives in allauth).",
                        max_length=2000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="users.tenantconnection",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("credential_type", "oauth")),
                fields=("user", "provider"),
                name="unique_oauth_connection_per_user_provider",
            ),
        ),
    ]
