# Generated by Django 5.2.11 on 2026-06-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_ocs_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcredential',
            name='team_id',
            field=models.CharField(blank=True, help_text='OCS team ID or other provider-specific team identifier. NULL for OAuth.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantcredential',
            name='team_name',
            field=models.CharField(blank=True, help_text='Display name for the team (e.g., OCS workspace name).', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantcredential',
            name='tenant_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='users.tenantmembership'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('credential_type', 'oauth'), ('team_id__isnull', True)), fields=('tenant_membership',), name='unique_oauth_credential_per_membership'),
        ),
    ]
