# Generated by Django 5.2.11 on 2026-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tenantcredential_team_id_tenantcredential_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantcredential',
            name='unique_oauth_credential_per_membership',
        ),
        migrations.AlterField(
            model_name='tenantcredential',
            name='team_id',
            field=models.CharField(blank=True, default='', help_text='OCS team ID or other provider-specific team identifier. Empty for OAuth.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='tenantcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('credential_type', 'oauth'), ('team_id', '')), fields=('tenant_membership',), name='unique_oauth_credential_per_membership'),
        ),
    ]
