# Generated by Django 5.2.11 on 2026-06-05 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_migrate_credentials_to_connections"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TenantCredential",
        ),
    ]
