# Generated by Django 5.2.11 on 2026-07-02 13:15

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_tenantcredential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantmembership',
            options={'base_manager_name': 'all_objects', 'ordering': ['-last_selected_at', 'tenant__canonical_name']},
        ),
        migrations.AlterModelManagers(
            name='tenantmembership',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
