# Generated by Django 5.2.11 on 2026-09-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_scope_tenant_connection_to_a_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconnection",
            name="oauth_refresh_failure_fingerprint",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Internal fingerprint of the OAuth credential whose last refresh failed.",
                max_length=64,
            ),
        ),
    ]
