# Generated by Django 5.2.11 on 2026-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_oauth_refresh_failure_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconnection",
            name="upstream_denial_code",
            field=models.CharField(blank=True, db_default="", default="", max_length=40),
        ),
        migrations.AddField(
            model_name="tenantconnection",
            name="upstream_denied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
