# Generated by Django 5.2.11 on 2026-09-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_verification_attempt_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcontrol",
            name="last_attempt_tenant_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tenant ids the last attempt's outcome is authoritative for, as strings. The lease is per connection, so this is what stops a waiter reusing a receipt from an attempt that never covered its tenants.",
            ),
        ),
    ]
