# Generated by Django 5.2.11 on 2026-10-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_tenantmembership_archived_reason"),
        ("workspaces", "0021_workspaceloadtiming"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
    ]
