# Generated by Django 5.2.11 on 2026-06-28 18:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0005_add_view_schema_last_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('error', 'Error')], default='active', max_length=20)),
                ('diagnostics', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_model', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace__name'],
            },
        ),
        migrations.CreateModel(
            name='SemanticDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schema_name', models.CharField(blank=True, max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('primary_key', models.CharField(blank=True, max_length=255)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_datasets', to='workspaces.workspace')),
                ('semantic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='semantic.semanticmodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SemanticCanvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('committed', 'Committed'), ('discarded', 'Discarded')], default='open', max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=list)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_canvases', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_canvases', to='workspaces.workspace')),
                ('semantic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='semantic.semanticmodel')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SemanticRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=255)),
                ('relationship_type', models.CharField(choices=[('one_to_one', 'One to one'), ('one_to_many', 'One to many'), ('many_to_one', 'Many to one')], default='many_to_one', max_length=30)),
                ('join_expression', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='semantic.semanticdataset')),
                ('to_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='semantic.semanticdataset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_relationships', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SemanticField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('field_type', models.CharField(choices=[('dimension', 'Dimension'), ('time_dimension', 'Time dimension'), ('measure', 'Measure')], max_length=30)),
                ('data_type', models.CharField(blank=True, max_length=100)),
                ('expression', models.CharField(help_text='Trusted column name or expression generated by Scout.', max_length=500)),
                ('measure_type', models.CharField(blank=True, choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum'), ('number', 'Number')], max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='semantic.semanticdataset')),
            ],
            options={
                'ordering': ['field_type', 'name'],
                'indexes': [models.Index(fields=['dataset', 'field_type', 'is_visible'], name='semantic_se_dataset_780cca_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'name'), name='unique_semantic_field_name_per_dataset')],
            },
        ),
        migrations.AddIndex(
            model_name='semanticdataset',
            index=models.Index(fields=['workspace', 'is_visible'], name='semantic_se_workspa_ea0379_idx'),
        ),
        migrations.AddConstraint(
            model_name='semanticdataset',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_semantic_dataset_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='semanticcanvas',
            index=models.Index(fields=['workspace', 'status'], name='semantic_se_workspa_ad6519_idx'),
        ),
        migrations.AddConstraint(
            model_name='semanticrelationship',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_semantic_relationship_name_per_workspace'),
        ),
    ]
