# Generated by Django 5.2.11 on 2026-06-30 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0001_initial'),
        ('workspaces', '0005_add_view_schema_last_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticdataset',
            name='source_kind',
            field=models.CharField(choices=[('physical', 'Physical'), ('custom', 'Custom')], default='physical', max_length=20),
        ),
        migrations.CreateModel(
            name='CubeSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('error', 'Error')], default='active', max_length=20)),
                ('diagnostics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semantic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cube_schemas', to='semantic.semanticmodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cube_schemas', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='CustomDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('definition_sql', models.TextField(blank=True)),
                ('definition_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('error', 'Error')], default='active', max_length=20)),
                ('diagnostics', models.JSONField(blank=True, default=list)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_datasets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_datasets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='semanticdataset',
            name='custom_dataset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_dataset', to='semantic.customdataset'),
        ),
        migrations.AddIndex(
            model_name='semanticdataset',
            index=models.Index(fields=['workspace', 'source_kind', 'is_visible'], name='semantic_se_workspa_e636ee_idx'),
        ),
        migrations.AddIndex(
            model_name='cubeschema',
            index=models.Index(fields=['workspace', 'status'], name='semantic_cu_workspa_ea16a2_idx'),
        ),
        migrations.AddIndex(
            model_name='cubeschema',
            index=models.Index(fields=['semantic_model', 'status'], name='semantic_cu_semanti_0d632b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cubeschema',
            constraint=models.UniqueConstraint(fields=('workspace', 'filename'), name='unique_cube_schema_filename_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='cubeschema',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('workspace', 'semantic_model'), name='unique_active_cube_schema_per_model'),
        ),
        migrations.AddIndex(
            model_name='customdataset',
            index=models.Index(fields=['workspace', 'status', 'is_visible'], name='semantic_cu_workspa_fc2465_idx'),
        ),
        migrations.AddConstraint(
            model_name='customdataset',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_custom_dataset_name_per_workspace'),
        ),
    ]
