# Generated by Django 5.2.11 on 2026-09-30 05:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_remove_thread_sharing"),
        ("semantic", "0004_expand_measure_types"),
        ("workspaces", "0020_drop_workspace_data_dictionary_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticModelRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("canvas_commit", "Canvas commit"), ("undo", "Undo")],
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("changes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="semantic_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverts",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undo_revision",
                        to="semantic.semanticmodelrevision",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="semantic_revisions",
                        to="chat.thread",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_revisions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"], name="semantic_se_workspa_c7fc13_idx"
                    )
                ],
            },
        ),
    ]
