# Generated by Django 5.2.11 on 2026-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantic", "0006_semantic_model_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanticcanvas",
            name="pending_confirmations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
