"""Parent-facing Canvas Manager subagent tool.

The parent Scout agent sees a single ``canvas_manager`` tool and keeps only a
read-only ``canvas_read`` for itself. All canvas writes are delegated here: the
subagent runs the apply/diagnose loop with the canvas tools off-thread and only
a compact report (what changed, diagnostics state, committed-or-not) returns to
the parent — the op churn never lands in the parent's context.
"""

from __future__ import annotations

import copy
import json
import logging
import uuid
from typing import TYPE_CHECKING, Any, Literal

from django.conf import settings
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import tool
from langgraph.errors import GraphRecursionError
from langgraph.graph import END, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from pydantic import BaseModel, Field

from apps.agents.graph.state import AgentState
from apps.agents.subagents.events import (
    SUBAGENT_EVENT_QUEUE_CONFIG_KEY,
    reset_subagent_event_queue,
    set_subagent_event_queue,
)
from apps.agents.subagents.forwarding import NestedEventForwarder
from apps.agents.tools.canvas_tool import create_canvas_tools

if TYPE_CHECKING:
    from apps.users.models import User
    from apps.workspaces.models import Workspace

logger = logging.getLogger(__name__)

SUBAGENT_NAME = "canvas_manager"
NESTED_MCP_TOOL_NAMES = frozenset({"list_datasets", "describe_dataset", "semantic_query"})
NESTED_RECURSION_LIMIT = 18
NESTED_MAX_TOKENS = 4096


class CanvasManagerInput(BaseModel):
    task: str = Field(
        description=(
            "Complete, self-contained canvas task: which datasets to edit, exact "
            "fields/measures/dimensions to add (names, types, source columns), "
            "value formats/currency to set, relationships to link, CTE dataset "
            "SQL, and whether to commit."
        )
    )
    intent: str | None = Field(
        default=None,
        description="Optional terse intent label such as edit, add_fields, link, cte, or commit.",
    )
    # Injected by the parent graph; hidden from the model-facing schema.
    tool_call_id: str | None = None
    subagent_event_queue: Any | None = None


CANVAS_MANAGER_SYSTEM_PROMPT = """
You are Scout's Canvas Manager subagent. You execute semantic-canvas work for a
parent agent: staging and committing changes to the workspace's datasets. Be
concise and deterministic.

The canvas is a changeset of pending edits over the saved semantic model,
shared with the user in a side panel. Your tools:
- `canvas_read(selector)` — 'graph' (objects + states), 'diff', 'diagnostics', or 'all'.
- `canvas_sample_rows(dataset, limit, fields)` — inspect a small saved-dataset
  sample through the semantic model when column names/types are not enough to
  choose labels, descriptions, value/display formats, or currency codes.
- `canvas_apply(operations)` — the ONLY write path: one atomic batch of ops.
  Returns applied ops + current diagnostics; invalid batches return `errors`
  and write nothing.
- `canvas_commit()` — persist the changeset to the semantic model and rebuild
  the Cube schema. Blocked while error diagnostics remain.
- `list_datasets`, `describe_dataset`, `semantic_query` — discover datasets and
  their columns/members; verify committed members are queryable.

## What the canvas can change (hard rules, enforced server-side)
- Datasets: label and description edits only.
- Fields: ADD new dimensions and measures. Autogenerated fields accept only
  label/description/format/currency curation and can NEVER be deleted or
  retyped. Only fields created through the canvas are fully editable/deletable.
- Field value format / display format is field-level metadata, valid on BOTH
  dimensions and measures. Set it with `format` (`number`, `number_0`,
  `number_2`, `percent_1`, `currency_2`, `abbr_1`, `accounting_2`, or a compact
  d3 spec) and optional 3-letter ISO `currency` such as `USD`. If a user says
  "value format", "number format", "decimal places", "decimal_02", "USD", or
  "currency", they are talking about this metadata. `decimal_02` means
  `number_2`; USD means `currency: "USD"` and usually `format: "currency_2"`
  for monetary fields.
- A standard aggregate measure's `expression` must be an existing COLUMN of
  the dataset (use `describe_dataset` to find columns).
- A dimension/time_dimension's `expression` also names an existing COLUMN.
  For a row-level calculation, use `sql` (alias `cube_sql`) instead, for example
  `sql: "CASE WHEN {CUBE}.\"amount\" > 0 THEN 'Paid' ELSE 'Unpaid' END"`, with
  `field_type: "dimension"` and `data_type: "text"`. Calculated dimensions
  preserve row grain and use this dataset's columns, either bare or as
  `{CUBE}."column"`; they cannot reference measures, other datasets, aggregates,
  subqueries, or window functions. `filters` remains a measure-only option.
- Calculated and ratio measures use `measure_type: "number"` with `sql` (an
  alias for `cube_sql`) instead of `expression`. Reference measures as
  `{member_name}`. Create any dependency measures in the same batch. For
  example, an approval rate can use a filtered count named
  `approved_visit_count`, then `sql: "{approved_visit_count} / NULLIF({count}, 0)"`
  would perform integer division in PostgreSQL. Cast one operand explicitly:
  `sql: "{approved_visit_count}::numeric / NULLIF({count}, 0)"` with
  `format: "percent_1"`. Always force decimal division for ratios of count
  measures. Use `{CUBE}."column"` only when the calculation
  truly needs a physical column. Do not put aggregate SQL in `expression`.
- Use a CTE dataset when computed logic changes the dataset's row grain or
  requires joins, subqueries, or windows. Row-level calculated dimensions and
  calculated measures do not by themselves need a CTE dataset.
- Relationships: ADD links between datasets (from_field/to_field must be real
  fields). Pipeline-derived relationships are protected.
- CTE datasets: create with `definition_sql` (a single SELECT/WITH query over
  this workspace's datasets; no schema prefixes) and a `primary_key` naming
  one of the query's output columns (a column literally named `id` is used by
  default; every dataset needs a primary key — pick the column that uniquely
  identifies a row, e.g. the GROUP BY column). SQL is validated and columns
  inferred immediately — fix reported problems before committing. On committed
  CTE datasets, primary_key stays editable via
  {"op": "set", "target": "dataset/<name>/primary_key", "value": "..."}.
  Output dimensions, time dimensions, and a count measure are autogenerated
  on commit. Do NOT recreate these fields. A pending dataset is not yet visible
  to describe_dataset or field operations: create the dataset WITHOUT field
  operations, use canvas_read for inferred output columns, commit only when
  authorized, then describe_dataset and curate the saved fields or add extra
  measures. If only staging is authorized, report the remaining field work
  instead of committing. Dataset draft metadata can use dataset/<name> or
  custom_dataset/<name> targets.
- For transcript-derived topic datasets, use only the classification rules or
  reviewed labels provided/approved by the parent and user. Do not invent a
  taxonomy from column names. Preserve the source message ID as the primary
  key for message-grain results and retain its time column for dashboard
  filters. Document keyword rules versus reviewed snapshot labels and their
  coverage; new messages do not automatically receive snapshot labels.
  Reusable keyword-rule SQL is NOT a fixed snapshot: it evaluates the current
  materialized rows, including newly materialized messages. Reviewed message-ID
  label mappings remain limited to their snapshot. Inspect the source dataset's
  `metadata.identity` before persisting reviewed labels. If it marks identity
  unsafe for reviewed labels, stop and request an authorized source refresh.
  For snapshot-local identity, retain the full versioned key, snapshot column,
  and content-version column; never strip the revision or join labels by row
  position. Match reviewed labels by key AND content version, keep unmatched
  rows unclassified, and disclose that any history change requires re-review.

## canvas_apply op reference
- {"op": "add_existing", "object_type": "dataset", "ref": "raw_visits"}
- {"op": "set", "target": "dataset/raw_visits/description", "value": "..."}
- {"op": "set", "target": "field/raw_visits.amount/label", "value": "Amount (USD)"}
- {"op": "set", "target": "field/raw_visits.amount/format", "value": "currency_2"}
- {"op": "set", "target": "field/raw_visits.amount/currency", "value": "USD"}
- {"op": "create", "object_type": "field", "value": {"dataset": "raw_visits",
   "name": "total_amount", "label": "Total Amount", "field_type": "measure",
   "measure_type": "sum", "expression": "amount", "format": "currency_2",
   "currency": "USD"}}
- {"op": "create", "object_type": "field", "value": {"dataset": "raw_visits",
   "name": "approval_rate", "label": "Approval Rate", "field_type": "measure",
   "measure_type": "number", "sql":
   "{approved_visit_count}::numeric / NULLIF({count}, 0)", "format": "percent_1"}}
- {"op": "create", "object_type": "relationship", "value": {"from_dataset":
   "raw_visits", "from_field": "username", "to_dataset": "raw_users",
   "to_field": "username", "relationship_type": "many_to_one"}}
- {"op": "create", "object_type": "custom_dataset", "value": {"name":
   "visit_stats", "label": "Visit Stats", "primary_key": "username",
   "definition_sql":
   "with s as (select username, count(*) n from raw_visits group by 1) select * from s"}}
- {"op": "delete_object", "object": "field/<uuid-or-dataset.name>"}  (canvas-created only)
- {"op": "remove_from_canvas", "object": "dataset/raw_visits"}  (discard pending changes)
- {"op": "revert_object", "object": "dataset/raw_visits"}  (back to saved state)

## Working rules
1. Orient with `canvas_read('graph')` only when the task doesn't already tell
   you the state. Use `describe_dataset` before creating fields so expressions
   name real columns.
   Use `canvas_sample_rows` when a requested labeling/value-formatting decision
   needs examples of actual values.
2. Plan the whole change and send it as ONE `canvas_apply` batch when possible.
   Creating a dataset and editing its generated fields require separate batches
   with an authorized commit in between. Never retry the same rejected batch.
3. Trust each apply's returned diagnostics — do not re-read what it showed you.
4. Try a bounded correction for error diagnostics your ops introduced. If the
   same error recurs, report blocked with the remaining diagnostics rather than
   looping. Do not discard pending changes automatically.
5. Commit only when the task says to (save/commit/publish). If commit reports
   blocked or conflicts, fix what it lists or report back — never discard
   someone else's changes on your own.

## Final response (REQUIRED — this is ALL the parent sees)
Return a compact JSON object in text with keys:
`status` ("done" | "blocked" | "error"), `message` (1-3 sentences),
`changes` (one short line per object touched), `diagnostics` (remaining
problems, empty when clean), `committed` (true/false).
Never paste raw tool output or SQL bodies unless the task asked for them.
"""


def create_canvas_manager_tool(
    workspace: Workspace,
    user: User | None,
    mcp_tools: list,
    conversation_id: str | None = None,
):
    """Create the parent-facing Canvas Manager tool."""

    @tool(args_schema=CanvasManagerInput)
    async def canvas_manager(
        task: str,
        intent: str | None = None,
        tool_call_id: str | None = None,
        subagent_event_queue: Any | None = None,
    ) -> dict[str, Any]:
        """Delegate semantic canvas work (dataset edits, new fields/measures,
        relationships, CTE datasets, commits) to the Canvas Manager subagent."""
        parent_tool_call_id = tool_call_id or f"missing-parent-{uuid.uuid4().hex[:8]}"
        queue_token = set_subagent_event_queue(subagent_event_queue)
        prompt = f"Task: {task.strip()}" + (f"\nIntent: {intent}" if intent else "")
        input_state = {
            "messages": [HumanMessage(content=prompt)],
            "workspace_id": str(workspace.id),
            "user_id": str(user.id) if user else "",
            "user_role": "analyst",
            "thread_id": conversation_id or "",
        }
        config = {
            "configurable": {"thread_id": f"{conversation_id or 'canvas'}:canvas-manager"},
            "recursion_limit": NESTED_RECURSION_LIMIT,
            "run_name": SUBAGENT_NAME,
            "tags": ["subagent", SUBAGENT_NAME],
            "metadata": {
                "subagent": SUBAGENT_NAME,
                "parent_tool_call_id": parent_tool_call_id,
                "workspace_id": str(workspace.id),
                "conversation_id": conversation_id or "",
            },
        }
        forwarder = NestedEventForwarder(SUBAGENT_NAME, parent_tool_call_id)
        messages: list[Any] = []
        unfinished_commits: set[str] = set()
        try:
            await forwarder.status(phase="running", message="Canvas Manager started.")
            graph = _build_canvas_manager_graph(workspace, user, mcp_tools, conversation_id)
            async for event in graph.astream_events(input_state, config=config, version="v2"):
                await forwarder.forward(event)
                output = event.get("data", {}).get("output")
                if event.get("name") == "canvas_commit":
                    run_id = str(event.get("run_id") or "canvas_commit")
                    if event.get("event") == "on_tool_start":
                        unfinished_commits.add(run_id)
                    elif event.get("event") == "on_tool_end":
                        report = _parse_json_object(getattr(output, "content", output)) or {}
                        if "committed" in report or "errors" in report:
                            unfinished_commits.discard(run_id)
                if event.get("event") == "on_tool_end" and isinstance(output, ToolMessage):
                    messages = add_messages(messages, [output])
                if event.get("event") == "on_chain_end" and isinstance(output, dict):
                    maybe_messages = output.get("messages")
                    if isinstance(maybe_messages, list):
                        # Node outputs can contain only the newest AI message, not the history.
                        messages = add_messages(messages, maybe_messages)
            result = _summarize_result(messages)
            failed = result["status"] in {"blocked", "error"}
            await forwarder.status(
                phase="failed" if failed else "completed",
                message=result["message"] if failed else "Canvas Manager completed.",
                committed=result.get("committed"),
            )
            result["subagent_trace"] = forwarder.trace()
            return result
        except GraphRecursionError:
            logger.warning(
                "Canvas Manager step limit reached for workspace %s conversation %s",
                workspace.id,
                conversation_id,
            )
            return await _failure_result(
                forwarder, messages, "STEP_LIMIT_REACHED", bool(unfinished_commits)
            )
        except Exception:
            logger.exception(
                "Canvas Manager failed for workspace %s conversation %s",
                workspace.id,
                conversation_id,
            )
            return await _failure_result(
                forwarder, messages, "CANVAS_MANAGER_FAILED", bool(unfinished_commits)
            )
        finally:
            reset_subagent_event_queue(queue_token)

    canvas_manager.name = "canvas_manager"
    return canvas_manager


def _build_canvas_manager_graph(
    workspace: Workspace,
    user: User | None,
    mcp_tools: list,
    conversation_id: str | None,
):
    canvas_tools = create_canvas_tools(workspace, user, conversation_id or "")
    nested_mcp_tools = [
        tool_obj
        for tool_obj in mcp_tools
        if getattr(tool_obj, "name", None) in NESTED_MCP_TOOL_NAMES
    ]
    tools = [*canvas_tools, *nested_mcp_tools]
    tool_node = _make_nested_tool_node(ToolNode(tools))
    llm = ChatAnthropic(model=settings.DEFAULT_LLM_MODEL, max_tokens=NESTED_MAX_TOKENS)
    llm_with_tools = llm.bind_tools(_nested_llm_tool_schemas(tools))

    async def agent_node(state: AgentState) -> dict[str, Any]:
        state_messages = [m for m in list(state["messages"]) if not isinstance(m, SystemMessage)]
        messages = [SystemMessage(content=CANVAS_MANAGER_SYSTEM_PROMPT), *state_messages]
        response = await llm_with_tools.ainvoke(messages)
        return {"messages": [response]}

    def should_continue(state: AgentState) -> Literal["tools", "__end__"]:
        messages = state.get("messages", [])
        if not messages:
            return END
        last_message = messages[-1]
        if hasattr(last_message, "tool_calls") and last_message.tool_calls:
            return "tools"
        return END

    graph = StateGraph(AgentState)
    graph.add_node("agent", agent_node)
    graph.add_node("tools", tool_node)
    graph.set_entry_point("agent")
    graph.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
    graph.add_edge("tools", "agent")
    return graph.compile()


def _nested_llm_tool_schemas(tools: list) -> list:
    hidden = {
        "workspace_id",
        "user_id",
        "thread_id",
        "tool_call_id",
        "runtime",
        SUBAGENT_EVENT_QUEUE_CONFIG_KEY,
    }
    result = []
    for tool_obj in tools:
        schema = tool_obj.get_input_schema().model_json_schema()
        props = schema.get("properties", {})
        to_hide = hidden & set(props)
        if not to_hide:
            result.append(tool_obj)
            continue
        trimmed_props = {k: v for k, v in props.items() if k not in to_hide}
        trimmed_required = [r for r in schema.get("required", []) if r not in to_hide]
        result.append(
            {
                "type": "function",
                "function": {
                    "name": tool_obj.name,
                    "description": tool_obj.description or "",
                    "parameters": {
                        "type": "object",
                        "properties": trimmed_props,
                        "required": trimmed_required,
                    },
                },
            }
        )
    return result


def _make_nested_tool_node(base_tool_node: ToolNode):
    async def injecting_node(
        state: AgentState,
        config: RunnableConfig | None = None,
    ) -> dict[str, Any]:
        messages = list(state["messages"])
        last_msg = messages[-1]
        if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
            modified_msg = copy.copy(last_msg)
            modified_calls = []
            for tc in last_msg.tool_calls:
                if tc["name"] in NESTED_MCP_TOOL_NAMES:
                    tc_id = tc.get("id") or ""
                    extra = {
                        "workspace_id": state.get("workspace_id", ""),
                        "user_id": state.get("user_id", ""),
                        "thread_id": state.get("thread_id", ""),
                        "tool_call_id": tc_id,
                    }
                    tc = {**tc, "args": {**tc["args"], **extra}}
                modified_calls.append(tc)
            modified_msg.tool_calls = modified_calls
            messages = [*messages[:-1], modified_msg]
        return await base_tool_node.ainvoke({"messages": messages}, config=config)

    injecting_node.__annotations__["config"] = RunnableConfig | None
    return injecting_node


async def _failure_result(
    forwarder: NestedEventForwarder,
    messages: list[Any],
    error_code: str,
    commit_unconfirmed: bool,
) -> dict[str, Any]:
    result = _summarize_result(messages)
    reason = (
        "reached its step limit" if error_code == "STEP_LIMIT_REACHED" else "stopped unexpectedly"
    )
    message = f"Canvas Manager {reason} before completing the task. "
    if result["committed"]:
        message += "Some changes were committed and were not rolled back. "
    elif commit_unconfirmed:
        result["committed"] = None
        message += "A commit started but its outcome was not confirmed. "
    else:
        message += "No successful commit was observed during this delegation. "
    if commit_unconfirmed:
        result["pending_count"] = None
    result.update(
        status="error",
        error_code=error_code,
        commit_unconfirmed=commit_unconfirmed,
        message=(
            message + "Read the canvas to inspect remaining drafts and verify saved members/Cube "
            "before continuing. Do not recreate committed objects or discard drafts automatically."
        ),
    )
    await forwarder.forward(
        {
            "event": "on_chain_error",
            "run_id": f"{forwarder.parent_tool_call_id}:failure",
            "data": {"error": result["message"]},
        }
    )
    await forwarder.status(phase="failed", message=result["message"], committed=result["committed"])
    result["subagent_trace"] = forwarder.trace()
    return result


def _summarize_result(messages: list[Any]) -> dict[str, Any]:
    final_text = ""
    for message in reversed(messages):
        if isinstance(message, AIMessage) and message.content:
            final_text = _content_text(message.content)
            break
    parsed_final = _parse_json_object(final_text) or {}
    committed_objects: list[dict] = []
    seen_commits: set[str] = set()
    last_commit: dict[str, Any] = {}
    last_state: dict[str, Any] = {}
    last_errors: list = []
    pending_count = None
    for message in messages:
        if not isinstance(message, ToolMessage) or message.name not in {
            "canvas_apply",
            "canvas_commit",
        }:
            continue
        report = _parse_json_object(message.content) or {}
        if not report:
            continue
        last_errors = report.get("errors") or []
        if "diagnostics" in report or "committed" in report:
            last_state = report
        if "pending_count" in report:
            pending_count = report["pending_count"]
        elif (
            "committed" in report
            and not report.get("blocked")
            and not report.get("conflicts")
            and not last_errors
        ):
            pending_count = 0
        elif "committed" in report and pending_count == 0:
            pending_count = None
        committed = report.get("committed")
        if message.name != "canvas_commit" or not isinstance(committed, list) or not committed:
            continue
        last_commit = report
        for obj in committed:
            if not isinstance(obj, dict):
                continue
            identity = json.dumps(obj, sort_keys=True)
            if identity not in seen_commits:
                committed_objects.append(obj)
                seen_commits.add(identity)

    diagnostics = [
        *(last_state.get("blocking_diagnostics") or last_state.get("diagnostics") or []),
        *(last_state.get("conflicts") or []),
    ]
    if not last_state and isinstance(parsed_final.get("diagnostics"), list):
        diagnostics = parsed_final["diagnostics"]
    diagnostics = [*diagnostics, *last_errors]
    result = {
        "status": parsed_final.get("status") or ("done" if final_text else "error"),
        "message": str(parsed_final.get("message") or final_text or "Canvas manager completed.")[
            :1200
        ],
        "changes": parsed_final.get("changes")
        or [
            f"{obj.get('object_type', 'object')}/{obj.get('name') or obj.get('object_uuid', '')}"
            for obj in committed_objects
        ],
        "diagnostics": diagnostics,
        "committed": bool(committed_objects),
        "committed_objects": committed_objects,
        "pending_count": pending_count,
    }
    problems = []
    blocked = (
        last_state.get("blocked")
        or last_state.get("blocking_diagnostics")
        or last_state.get("conflicts")
        or any(
            diagnostic.get("severity") == "error"
            for diagnostic in last_state.get("diagnostics") or []
        )
    )
    if blocked:
        result["status"] = "blocked"
        problems.append("Remaining canvas changes are blocked by diagnostics or conflicts.")
    if last_errors:
        result["status"] = "error"
        problems.append("The latest canvas operation failed.")
    if last_commit.get("cube_schema"):
        result["cube_schema"] = last_commit["cube_schema"]
        if result["cube_schema"].get("ok") is False:
            result["status"] = "error"
            problems.append("Cube schema promotion failed.")
    if problems:
        commit_state = (
            "Some semantic changes were committed and were not rolled back. "
            if committed_objects
            else "No successful commit was observed during this delegation. "
        )
        result["message"] = (
            commit_state + " ".join(problems) + " Inspect the remaining diagnostics and verify "
            "saved members and the active Cube schema before continuing."
        )
    return result


def _content_text(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return "\n".join(
            str(block.get("text", ""))
            for block in value
            if isinstance(block, dict) and block.get("type") == "text"
        )
    return ""


def _parse_json_object(value: Any) -> dict[str, Any] | None:
    if isinstance(value, dict):
        return value
    if isinstance(value, list):
        value = _content_text(value)
    if not isinstance(value, str):
        return None
    text = value.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if "\n" in text:
            text = text.split("\n", 1)[1]
    try:
        parsed = json.loads(text)
    except (TypeError, ValueError):
        return None
    return parsed if isinstance(parsed, dict) else None
