"""Parent-facing Canvas Manager subagent tool.

The parent Scout agent sees a single ``canvas_manager`` tool and keeps only a
read-only ``canvas_read`` for itself. All canvas writes are delegated here: the
subagent runs the apply/diagnose loop with the canvas tools off-thread and only
a compact report (what changed, diagnostics state, committed-or-not) returns to
the parent — the op churn never lands in the parent's context.
"""

from __future__ import annotations

import copy
import json
import logging
import uuid
from typing import TYPE_CHECKING, Any, Literal

from django.conf import settings
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import tool
from langgraph.graph import END, StateGraph
from langgraph.prebuilt import ToolNode
from pydantic import BaseModel, Field

from apps.agents.graph.state import AgentState
from apps.agents.subagents.events import (
    SUBAGENT_EVENT_QUEUE_CONFIG_KEY,
    reset_subagent_event_queue,
    set_subagent_event_queue,
)
from apps.agents.subagents.forwarding import NestedEventForwarder
from apps.agents.tools.canvas_tool import create_canvas_tools

if TYPE_CHECKING:
    from apps.users.models import User
    from apps.workspaces.models import Workspace

logger = logging.getLogger(__name__)

SUBAGENT_NAME = "canvas_manager"
NESTED_MCP_TOOL_NAMES = frozenset({"list_datasets", "describe_dataset", "semantic_query"})
NESTED_RECURSION_LIMIT = 18
NESTED_MAX_TOKENS = 4096


class CanvasManagerInput(BaseModel):
    task: str = Field(
        description=(
            "Complete, self-contained canvas task: which datasets to edit, exact "
            "fields/measures/dimensions to add (names, types, source columns), "
            "value formats/currency to set, relationships to link, CTE dataset "
            "SQL, and whether to commit."
        )
    )
    intent: str | None = Field(
        default=None,
        description="Optional terse intent label such as edit, add_fields, link, cte, or commit.",
    )
    # Injected by the parent graph; hidden from the model-facing schema.
    tool_call_id: str | None = None
    subagent_event_queue: Any | None = None


CANVAS_MANAGER_SYSTEM_PROMPT = """
You are Scout's Canvas Manager subagent. You execute semantic-canvas work for a
parent agent: staging and committing changes to the workspace's datasets. Be
concise and deterministic.

The canvas is a changeset of pending edits over the saved semantic model,
shared with the user in a side panel. Your tools:
- `canvas_read(selector)` — 'graph' (objects + states), 'diff', 'diagnostics', or 'all'.
- `canvas_sample_rows(dataset, limit, fields)` — inspect a small saved-dataset
  sample through the semantic model when column names/types are not enough to
  choose labels, descriptions, value/display formats, or currency codes.
- `canvas_apply(operations)` — the ONLY write path: one atomic batch of ops.
  Returns applied ops + current diagnostics; invalid batches return `errors`
  and write nothing.
- `canvas_commit()` — persist the changeset to the semantic model and rebuild
  the Cube schema. Blocked while error diagnostics remain.
- `list_datasets`, `describe_dataset`, `semantic_query` — discover datasets and
  their columns/members; verify committed members are queryable.

## What the canvas can change (hard rules, enforced server-side)
- Datasets: label and description edits only.
- Fields: ADD new dimensions and measures. Autogenerated fields accept only
  label/description/format/currency curation and can NEVER be deleted or
  retyped. Only fields created through the canvas are fully editable/deletable.
- Field value format / display format is field-level metadata, valid on BOTH
  dimensions and measures. Set it with `format` (`number`, `number_0`,
  `number_2`, `percent_1`, `currency_2`, `abbr_1`, `accounting_2`, or a compact
  d3 spec) and optional 3-letter ISO `currency` such as `USD`. If a user says
  "value format", "number format", "decimal places", "decimal_02", "USD", or
  "currency", they are talking about this metadata. `decimal_02` means
  `number_2`; USD means `currency: "USD"` and usually `format: "currency_2"`
  for monetary fields.
- A new field's `expression` must be an existing COLUMN of the dataset (use
  `describe_dataset` to find columns). For computed logic, create a CTE
  dataset instead.
- Relationships: ADD links between datasets (from_field/to_field must be real
  fields). Pipeline-derived relationships are protected.
- CTE datasets: create with `definition_sql` (a single SELECT/WITH query over
  this workspace's datasets; no schema prefixes) and a `primary_key` naming
  one of the query's output columns (a column literally named `id` is used by
  default; every dataset needs a primary key — pick the column that uniquely
  identifies a row, e.g. the GROUP BY column). SQL is validated and columns
  inferred immediately — fix reported problems before committing. On committed
  CTE datasets, primary_key stays editable via
  {"op": "set", "target": "dataset/<name>/primary_key", "value": "..."}.

## canvas_apply op reference
- {"op": "add_existing", "object_type": "dataset", "ref": "raw_visits"}
- {"op": "set", "target": "dataset/raw_visits/description", "value": "..."}
- {"op": "set", "target": "field/raw_visits.amount/label", "value": "Amount (USD)"}
- {"op": "set", "target": "field/raw_visits.amount/format", "value": "currency_2"}
- {"op": "set", "target": "field/raw_visits.amount/currency", "value": "USD"}
- {"op": "create", "object_type": "field", "value": {"dataset": "raw_visits",
   "name": "total_amount", "label": "Total Amount", "field_type": "measure",
   "measure_type": "sum", "expression": "amount", "format": "currency_2",
   "currency": "USD"}}
- {"op": "create", "object_type": "relationship", "value": {"from_dataset":
   "raw_visits", "from_field": "username", "to_dataset": "raw_users",
   "to_field": "username", "relationship_type": "many_to_one"}}
- {"op": "create", "object_type": "custom_dataset", "value": {"name":
   "visit_stats", "label": "Visit Stats", "primary_key": "username",
   "definition_sql":
   "with s as (select username, count(*) n from raw_visits group by 1) select * from s"}}
- {"op": "delete_object", "object": "field/<uuid-or-dataset.name>"}  (canvas-created only)
- {"op": "remove_from_canvas", "object": "dataset/raw_visits"}  (discard pending changes)
- {"op": "revert_object", "object": "dataset/raw_visits"}  (back to saved state)

## Working rules
1. Orient with `canvas_read('graph')` only when the task doesn't already tell
   you the state. Use `describe_dataset` before creating fields so expressions
   name real columns.
   Use `canvas_sample_rows` when a requested labeling/value-formatting decision
   needs examples of actual values.
2. Plan the whole change and send it as ONE `canvas_apply` batch when possible.
3. Trust each apply's returned diagnostics — do not re-read what it showed you.
4. Fix error diagnostics your ops introduced before finishing (further ops, or
   revert_object). Never finish with errors outstanding.
5. Commit only when the task says to (save/commit/publish). If commit reports
   blocked or conflicts, fix what it lists or report back — never discard
   someone else's changes on your own.

## Final response (REQUIRED — this is ALL the parent sees)
Return a compact JSON object in text with keys:
`status` ("done" | "blocked" | "error"), `message` (1-3 sentences),
`changes` (one short line per object touched), `diagnostics` (remaining
problems, empty when clean), `committed` (true/false).
Never paste raw tool output or SQL bodies unless the task asked for them.
"""


def create_canvas_manager_tool(
    workspace: Workspace,
    user: User | None,
    mcp_tools: list,
    conversation_id: str | None = None,
):
    """Create the parent-facing Canvas Manager tool."""

    @tool(args_schema=CanvasManagerInput)
    async def canvas_manager(
        task: str,
        intent: str | None = None,
        tool_call_id: str | None = None,
        subagent_event_queue: Any | None = None,
    ) -> dict[str, Any]:
        """Delegate semantic canvas work (dataset edits, new fields/measures,
        relationships, CTE datasets, commits) to the Canvas Manager subagent."""
        parent_tool_call_id = tool_call_id or f"missing-parent-{uuid.uuid4().hex[:8]}"
        queue_token = set_subagent_event_queue(subagent_event_queue)
        graph = _build_canvas_manager_graph(workspace, user, mcp_tools, conversation_id)
        prompt = f"Task: {task.strip()}" + (f"\nIntent: {intent}" if intent else "")
        input_state = {
            "messages": [HumanMessage(content=prompt)],
            "workspace_id": str(workspace.id),
            "user_id": str(user.id) if user else "",
            "user_role": "analyst",
            "thread_id": conversation_id or "",
        }
        config = {
            "configurable": {"thread_id": f"{conversation_id or 'canvas'}:canvas-manager"},
            "recursion_limit": NESTED_RECURSION_LIMIT,
            "run_name": SUBAGENT_NAME,
            "tags": ["subagent", SUBAGENT_NAME],
            "metadata": {
                "subagent": SUBAGENT_NAME,
                "parent_tool_call_id": parent_tool_call_id,
                "workspace_id": str(workspace.id),
                "conversation_id": conversation_id or "",
            },
        }
        forwarder = NestedEventForwarder(SUBAGENT_NAME, parent_tool_call_id)
        messages: list[Any] = []
        try:
            await forwarder.status(phase="running", message="Canvas Manager started.")
            async for event in graph.astream_events(input_state, config=config, version="v2"):
                await forwarder.forward(event)
                output = event.get("data", {}).get("output")
                if event.get("event") == "on_chain_end" and isinstance(output, dict):
                    maybe_messages = output.get("messages")
                    if isinstance(maybe_messages, list):
                        messages = maybe_messages
        finally:
            reset_subagent_event_queue(queue_token)
        result = _summarize_result(messages)
        await forwarder.status(
            phase="completed",
            message="Canvas Manager completed.",
            committed=result.get("committed"),
        )
        result["subagent_trace"] = forwarder.trace()
        return result

    canvas_manager.name = "canvas_manager"
    return canvas_manager


def _build_canvas_manager_graph(
    workspace: Workspace,
    user: User | None,
    mcp_tools: list,
    conversation_id: str | None,
):
    canvas_tools = create_canvas_tools(workspace, user, conversation_id or "")
    nested_mcp_tools = [
        tool_obj
        for tool_obj in mcp_tools
        if getattr(tool_obj, "name", None) in NESTED_MCP_TOOL_NAMES
    ]
    tools = [*canvas_tools, *nested_mcp_tools]
    tool_node = _make_nested_tool_node(ToolNode(tools))
    llm = ChatAnthropic(model=settings.DEFAULT_LLM_MODEL, max_tokens=NESTED_MAX_TOKENS)
    llm_with_tools = llm.bind_tools(_nested_llm_tool_schemas(tools))

    async def agent_node(state: AgentState) -> dict[str, Any]:
        state_messages = [m for m in list(state["messages"]) if not isinstance(m, SystemMessage)]
        messages = [SystemMessage(content=CANVAS_MANAGER_SYSTEM_PROMPT), *state_messages]
        response = await llm_with_tools.ainvoke(messages)
        return {"messages": [response]}

    def should_continue(state: AgentState) -> Literal["tools", "__end__"]:
        messages = state.get("messages", [])
        if not messages:
            return END
        last_message = messages[-1]
        if hasattr(last_message, "tool_calls") and last_message.tool_calls:
            return "tools"
        return END

    graph = StateGraph(AgentState)
    graph.add_node("agent", agent_node)
    graph.add_node("tools", tool_node)
    graph.set_entry_point("agent")
    graph.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
    graph.add_edge("tools", "agent")
    return graph.compile()


def _nested_llm_tool_schemas(tools: list) -> list:
    hidden = {
        "workspace_id",
        "user_id",
        "thread_id",
        "tool_call_id",
        "runtime",
        SUBAGENT_EVENT_QUEUE_CONFIG_KEY,
    }
    result = []
    for tool_obj in tools:
        schema = tool_obj.get_input_schema().model_json_schema()
        props = schema.get("properties", {})
        to_hide = hidden & set(props)
        if not to_hide:
            result.append(tool_obj)
            continue
        trimmed_props = {k: v for k, v in props.items() if k not in to_hide}
        trimmed_required = [r for r in schema.get("required", []) if r not in to_hide]
        result.append(
            {
                "type": "function",
                "function": {
                    "name": tool_obj.name,
                    "description": tool_obj.description or "",
                    "parameters": {
                        "type": "object",
                        "properties": trimmed_props,
                        "required": trimmed_required,
                    },
                },
            }
        )
    return result


def _make_nested_tool_node(base_tool_node: ToolNode):
    async def injecting_node(
        state: AgentState,
        config: RunnableConfig | None = None,
    ) -> dict[str, Any]:
        messages = list(state["messages"])
        last_msg = messages[-1]
        if hasattr(last_msg, "tool_calls") and last_msg.tool_calls:
            modified_msg = copy.copy(last_msg)
            modified_calls = []
            for tc in last_msg.tool_calls:
                if tc["name"] in NESTED_MCP_TOOL_NAMES:
                    tc_id = tc.get("id") or ""
                    extra = {
                        "workspace_id": state.get("workspace_id", ""),
                        "user_id": state.get("user_id", ""),
                        "thread_id": state.get("thread_id", ""),
                        "tool_call_id": tc_id,
                    }
                    tc = {**tc, "args": {**tc["args"], **extra}}
                modified_calls.append(tc)
            modified_msg.tool_calls = modified_calls
            messages = [*messages[:-1], modified_msg]
        return await base_tool_node.ainvoke({"messages": messages}, config=config)

    injecting_node.__annotations__["config"] = RunnableConfig | None
    return injecting_node


def _summarize_result(messages: list[Any]) -> dict[str, Any]:
    final_text = ""
    for message in reversed(messages):
        if isinstance(message, AIMessage) and message.content:
            final_text = (
                message.content if isinstance(message.content, str) else str(message.content)
            )
            break
    parsed_final = _parse_json_object(final_text) or {}
    commit_result = _last_tool_result(messages, "canvas_commit")
    apply_result = _last_tool_result(messages, "canvas_apply")

    committed = bool(commit_result.get("committed")) if commit_result else False
    diagnostics = parsed_final.get("diagnostics")
    if not isinstance(diagnostics, list):
        source = commit_result or apply_result or {}
        diagnostics = source.get("blocking_diagnostics") or source.get("diagnostics") or []
    return {
        "status": parsed_final.get("status") or ("done" if final_text else "error"),
        "message": str(parsed_final.get("message") or final_text or "Canvas manager completed.")[
            :1200
        ],
        "changes": parsed_final.get("changes") or [],
        "diagnostics": diagnostics,
        "committed": bool(parsed_final.get("committed", committed)),
    }


def _last_tool_result(messages: list[Any], tool_name: str) -> dict[str, Any]:
    for message in reversed(messages):
        if isinstance(message, ToolMessage) and message.name == tool_name:
            parsed = _parse_json_object(message.content)
            return parsed if isinstance(parsed, dict) else {}
    return {}


def _parse_json_object(value: Any) -> dict[str, Any] | None:
    if isinstance(value, dict):
        return value
    if not isinstance(value, str):
        return None
    text = value.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if "\n" in text:
            text = text.split("\n", 1)[1]
    try:
        parsed = json.loads(text)
    except (TypeError, ValueError):
        return None
    return parsed if isinstance(parsed, dict) else None
