# Generated by Django 5.2.11 on 2026-05-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materializationrun",
            name="procrastinate_job_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="materializationrun",
            name="progress",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materializationrun",
            name="state",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("discovering", "Discovering"),
                    ("loading", "Loading"),
                    ("transforming", "Transforming"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="started",
                max_length=20,
            ),
        ),
    ]
