# Generated by Django 5.2.11 on 2026-06-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_alter_materializationrun_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceviewschema",
            name="last_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Most recent build_view_schema failure message; cleared on a successful build.",
            ),
        ),
    ]
