# Generated by Django 5.2.11 on 2026-09-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0006_workspaceinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceviewschema",
            name="tenant_coverage",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Tenants included in and excluded from the most recent view-schema build."
                ),
            ),
        ),
    ]
