# Generated by Django 5.2.11 on 2026-09-14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0010_workspaceviewschema_tenant_coverage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDataRecovery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recovery_type",
                    models.CharField(
                        choices=[
                            ("materialization", "Materialization"),
                            ("semantic_rebuild", "Semantic rebuild"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_type", models.CharField(default="artifact", max_length=32)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "procrastinate_job_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_workspace_data_recoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_recoveries",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="workspacedatarecovery",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["pending", "running"])),
                fields=("workspace",),
                name="one_active_data_recovery_per_workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacedatarecovery",
            index=models.Index(
                fields=["workspace", "state"],
                name="ws_recovery_ws_state",
            ),
        ),
    ]
