# Generated by Django 5.2.11 on 2026-09-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_verification_attempt_tenant_scope"),
        ("workspaces", "0014_workspaceviewschema_physical_build_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantschema",
            name="load_config_fingerprint",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.AddField(
            model_name="tenantschema",
            name="load_generation",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantschema",
            name="load_job_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantschema",
            name="load_workspace_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TenantLoadGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("requested_generation", models.BigIntegerField(default=0)),
                ("published_generation", models.BigIntegerField(default=0)),
                ("loading_generation", models.BigIntegerField(default=0)),
                ("published_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workspaces.materializationrun",
                    ),
                ),
                (
                    "published_schema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workspaces.tenantschema",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_generation",
                        to="users.tenant",
                    ),
                ),
            ],
        ),
    ]
