# Generated by Django 5.2.11 on 2026-09-29 05:58

from django.db import migrations, models

STATE_CHOICES = [
    ("provisioning", "Provisioning"),
    ("active", "Active"),
    ("expired", "Expired"),
    ("teardown", "Teardown"),
    ("failed", "Failed"),
]


def expire_materializing_rows(apps, schema_editor):
    # Nothing has written "materializing" (#251), but a stray row would otherwise
    # sit in a state no code reads. EXPIRED is the state provisioning already
    # resurrects and re-verifies, so no data is trusted without a check.
    for model in ("TenantSchema", "WorkspaceViewSchema"):
        apps.get_model("workspaces", model).objects.filter(state="materializing").update(
            state="expired"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0015_tenant_load_generation"),
    ]

    operations = [
        migrations.RunPython(expire_materializing_rows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tenantschema",
            name="state",
            field=models.CharField(choices=STATE_CHOICES, default="provisioning", max_length=20),
        ),
        migrations.AlterField(
            model_name="workspaceviewschema",
            name="state",
            field=models.CharField(choices=STATE_CHOICES, default="provisioning", max_length=20),
        ),
    ]
