# Generated by Django 5.2.11 on 2026-09-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_verification_attempt_tenant_scope"),
        ("workspaces", "0016_drop_materializing_schema_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacetenant",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspace_tenants",
                to="users.tenant",
            ),
        ),
    ]
