# Generated by Django 5.2.11 on 2026-09-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0018_retire_legacy_data_dictionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacetenant",
            name="last_load",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
