# Generated by Django 5.2.11 on 2026-10-05 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0020_drop_workspace_data_dictionary_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceLoadTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_id", models.BigIntegerField(unique=True)),
                ("only_unserved", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(null=True)),
                ("succeeded", models.BooleanField(default=False)),
                ("phase", models.CharField(default="loading", max_length=32)),
                ("phase_started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("phase_seconds", models.JSONField(default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "only_unserved", "succeeded", "-started_at"],
                        name="workspace_load_timing_history",
                    )
                ],
            },
        ),
    ]
