# Generated by Django 5.2.11 on 2026-06-19 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0002_add_name_validator'),
        ('workspaces', '0005_add_view_schema_last_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossOppMeasureLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_id', models.CharField(max_length=64)),
                ('measure', models.CharField(max_length=128)),
                ('column', models.CharField(blank=True, default='', max_length=255)),
                ('source_path', models.CharField(blank=True, default='', max_length=512)),
                ('matched_label', models.TextField(blank=True, default='')),
                ('sql_expression', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_lineage', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['measure', 'opportunity_id'],
                'unique_together': {('workspace', 'opportunity_id', 'measure')},
            },
        ),
    ]
