# Generated by Django 5.2.11 on 2026-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformations", "0002_add_name_validator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("tests_failed", "Tests Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
