# Generated by Django 5.2.11 on 2026-06-20 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0004_crossoppmeasure'),
        ('workspaces', '0005_add_view_schema_last_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossOppMeasureDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(default='numeric', max_length=16)),
                ('resolutions', models.JSONField(default=dict)),
                ('flagged', models.JSONField(default=list)),
                ('shortlists', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('thread_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_drafts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
