# Generated by Django 5.2.11 on 2026-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0005_crossoppmeasuredraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossoppmeasuredraft',
            name='target',
            field=models.CharField(default='measure', max_length=16),
        ),
    ]
