# Generated by Django 5.2.11 on 2026-10-08 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelemetryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("workspace_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("outcome", models.CharField(blank=True, default="", max_length=16)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("attrs", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["kind", "occurred_at"], name="telemetry_kind_time"),
                    models.Index(fields=["occurred_at"], name="telemetry_time"),
                ],
            },
        ),
    ]
