# Generated by Django 5.2.11 on 2026-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("metric", models.CharField(max_length=64)),
                ("dimension", models.CharField(blank=True, default="", max_length=64)),
                ("value", models.BigIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["metric", "day"], name="telemetry_snapshot_metric_day")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "metric", "dimension"), name="telemetry_snapshot_unique_day"
                    )
                ],
            },
        ),
    ]
