# Generated by Django 5.2.11 on 2026-10-08 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0002_dailysnapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telemetryevent",
            options={"permissions": [("view_usage_dashboard", "Can view the usage dashboard")]},
        ),
    ]
