# Generated by Django 5.2.11 on 2026-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial_recipe_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, accessible via public share link without authentication.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token for public share URL. Auto-generated when is_public is set.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reciperun',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, accessible via public share link without authentication.'),
        ),
        migrations.AddField(
            model_name='reciperun',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Visible to all project members.'),
        ),
        migrations.AddField(
            model_name='reciperun',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token for public share URL. Auto-generated when is_public is set.', max_length=64, null=True, unique=True),
        ),
    ]
