# Generated by Django 5.2.11 on 2026-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_is_public_recipe_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prompt',
            field=models.TextField(blank=True, default='', help_text='Prompt template with {{variable}} placeholders. Supports markdown.'),
        ),
    ]
