# Generated by Django 5.2.11 on 2026-02-12 18:31

from django.db import migrations


def migrate_steps_to_prompt(apps, schema_editor):
    """Concatenate RecipeStep prompt_templates into Recipe.prompt field."""
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeStep = apps.get_model("recipes", "RecipeStep")

    for recipe in Recipe.objects.all():
        steps = RecipeStep.objects.filter(recipe=recipe).order_by("order")
        if steps.exists() and not recipe.prompt:
            parts = []
            for step in steps:
                parts.append(step.prompt_template)
            recipe.prompt = "\n\n".join(parts)
            recipe.save(update_fields=["prompt"])


def reverse_migration(apps, schema_editor):
    """No-op reverse: steps still exist in the database."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_recipe_prompt_field'),
    ]

    operations = [
        migrations.RunPython(migrate_steps_to_prompt, reverse_migration),
    ]
