# Generated by Django 5.2.11 on 2026-09-29 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipestep_expected_tool"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recipe",
            name="recipes_rec_workspa_943bef_idx",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_shared",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="share_token",
        ),
        migrations.RemoveField(
            model_name="reciperun",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="reciperun",
            name="is_shared",
        ),
        migrations.RemoveField(
            model_name="reciperun",
            name="share_token",
        ),
    ]
