# Generated by Django 5.2.11 on 2026-03-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_migrate_tenant_workspaces"),
        ("recipes", "0006_recipe_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="projects.workspace",
            ),
        ),
    ]
