# Generated by Django 5.2.11 on 2026-06-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='semantic_queries',
            field=models.JSONField(blank=True, default=list, help_text='Structured semantic queries that generated the data for this artifact.'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('react', 'React Component'), ('html', 'HTML Document'), ('markdown', 'Markdown Document'), ('plotly', 'Plotly Chart'), ('svg', 'SVG Graphic'), ('story', 'Story')], help_text='The type of artifact (react, html, markdown, plotly, svg, story).', max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='source_queries',
            field=models.JSONField(blank=True, default=list, help_text='Legacy SQL queries that generated the data for this artifact.'),
        ),
    ]
