# Generated by Django 5.2.11 on 2026-03-06 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0003_rescope_to_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this artifact.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_artifacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
