# Generated by Codex on 2026-06-30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0004_alter_artifact_source_queries"),
        ("workspaces", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="semantic_query_manifest",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Normalized semantic query dependency manifest for graph artifacts.",
            ),
        ),
        migrations.CreateModel(
            name="ArtifactSemanticQuery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("query_key", models.CharField(max_length=500)),
                ("query_hash", models.CharField(db_index=True, max_length=64)),
                ("query_type", models.CharField(default="semantic", max_length=50)),
                ("validation_status", models.CharField(default="valid", max_length=50)),
                ("query_payload", models.JSONField(blank=True, default=dict)),
                ("members", models.JSONField(blank=True, default=list)),
                ("datasets", models.JSONField(blank=True, default=list)),
                ("dependencies", models.JSONField(blank=True, default=list)),
                ("block_locations", models.JSONField(blank=True, default=list)),
                ("unresolved_references", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_query_records",
                        to="artifacts.artifact",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_semantic_queries",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["query_key"],
            },
        ),
        migrations.AddConstraint(
            model_name="artifactsemanticquery",
            constraint=models.UniqueConstraint(
                fields=("artifact", "query_key"),
                name="unique_artifact_semantic_query_key",
            ),
        ),
        migrations.AddIndex(
            model_name="artifactsemanticquery",
            index=models.Index(fields=["workspace", "query_key"], name="artifacts_a_workspa_24aa43_idx"),
        ),
        migrations.AddIndex(
            model_name="artifactsemanticquery",
            index=models.Index(fields=["artifact", "query_key"], name="artifacts_a_artifac_3339f9_idx"),
        ),
    ]
