# Generated by Django 5.2.11 on 2026-03-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0007_remove_sharedartifact"),
        ("projects", "0019_migrate_tenant_workspaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="The workspace this artifact belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="projects.workspace",
            ),
        ),
    ]
