"""Object resolution and edit policy for the semantic canvas.

The canvas edits four object kinds. Policy summary (the user-facing contract):

- ``dataset``: label/description edits only. Datasets are never deleted from
  the model through the canvas, except committed CTE (custom) datasets.
- ``field``: new dimensions/measures can be created; autogenerated fields
  (built by ``ensure_semantic_model``) accept label/description curation but
  can never be deleted or structurally changed. Canvas-created fields
  (``metadata.source == "canvas"``) are fully editable and deletable.
- ``relationship``: new links between datasets can be created; pipeline-derived
  relationships (``metadata.generated``) are protected.
- ``custom_dataset``: a CTE/SQL-defined dataset draft; commits into a
  ``CustomDataset`` + a ``SemanticDataset`` with compiled SQL.
"""

from __future__ import annotations

import uuid
from typing import Any

from apps.semantic.models import (
    SemanticCanvasChange,
    SemanticDataset,
    SemanticField,
    SemanticRelationship,
)

CANVAS_SOURCE = "canvas"

DATASET_EDITABLE_KEYS = frozenset({"label", "description"})
FIELD_CURATION_KEYS = frozenset({"label", "description"})
FIELD_DRAFT_KEYS = frozenset(
    {"name", "label", "description", "field_type", "measure_type", "expression", "data_type"}
)
RELATIONSHIP_DRAFT_KEYS = frozenset(
    {
        "name",
        "from_dataset",
        "from_field",
        "to_dataset",
        "to_field",
        "relationship_type",
        "description",
    }
)
CUSTOM_DATASET_DRAFT_KEYS = frozenset(
    {"name", "label", "description", "definition_sql", "primary_key"}
)

FIELD_TYPES = {"dimension", "time_dimension", "measure"}
MEASURE_TYPES = {"count", "sum", "avg", "min", "max", "number"}
RELATIONSHIP_TYPES = {"one_to_one", "one_to_many", "many_to_one"}


class ObjectResolutionError(ValueError):
    """Raised when an op names an object that cannot be resolved."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


def is_canvas_created(obj) -> bool:
    metadata = getattr(obj, "metadata", None) or {}
    return metadata.get("source") == CANVAS_SOURCE


def is_generated_relationship(relationship: SemanticRelationship) -> bool:
    return bool((relationship.metadata or {}).get("generated"))


def _as_uuid(value: str) -> uuid.UUID | None:
    try:
        return uuid.UUID(str(value))
    except (TypeError, ValueError):
        return None


def resolve_dataset(model, ref: str) -> SemanticDataset:
    """Resolve a dataset by uuid or name among the model's visible datasets."""
    ref_uuid = _as_uuid(ref)
    qs = model.datasets.filter(is_visible=True)
    dataset = qs.filter(id=ref_uuid).first() if ref_uuid else qs.filter(name=ref).first()
    if dataset is None:
        raise ObjectResolutionError("OBJECT_NOT_FOUND", f"Unknown dataset '{ref}'.")
    return dataset


def resolve_field(model, ref: str) -> SemanticField:
    """Resolve a field by uuid or ``dataset.field`` member name."""
    ref_uuid = _as_uuid(ref)
    if ref_uuid:
        field = (
            SemanticField.objects.filter(id=ref_uuid, dataset__semantic_model=model)
            .select_related("dataset")
            .first()
        )
    elif "." in ref:
        dataset_name, field_name = ref.split(".", 1)
        field = (
            SemanticField.objects.filter(
                dataset__semantic_model=model,
                dataset__name=dataset_name,
                name=field_name,
            )
            .select_related("dataset")
            .first()
        )
    else:
        field = None
    if field is None:
        raise ObjectResolutionError(
            "OBJECT_NOT_FOUND", f"Unknown field '{ref}'. Use 'dataset.field' or a uuid."
        )
    return field


def resolve_relationship(workspace, ref: str) -> SemanticRelationship:
    ref_uuid = _as_uuid(ref)
    qs = SemanticRelationship.objects.filter(workspace=workspace)
    relationship = qs.filter(id=ref_uuid).first() if ref_uuid else qs.filter(name=ref).first()
    if relationship is None:
        raise ObjectResolutionError("OBJECT_NOT_FOUND", f"Unknown relationship '{ref}'.")
    return relationship


def dataset_column_names(dataset: SemanticDataset) -> set[str]:
    """Physical column names usable as a new field's expression."""
    columns: set[str] = set()
    for field in dataset.fields.all():
        source_column = (field.metadata or {}).get("source_column")
        if source_column:
            columns.add(source_column)
        elif field.expression and field.expression != "*":
            columns.add(field.expression)
    return columns


def serialize_dataset_base(dataset: SemanticDataset) -> dict[str, Any]:
    return {
        "name": dataset.name,
        "label": dataset.label,
        "description": dataset.description,
        "source_kind": dataset.source_kind,
    }


def serialize_field_base(field: SemanticField) -> dict[str, Any]:
    return {
        "name": field.name,
        "label": field.label,
        "description": field.description,
        "field_type": field.field_type,
        "measure_type": field.measure_type,
        "expression": field.expression,
        "data_type": field.data_type,
        "dataset": field.dataset.name,
    }


def serialize_relationship_base(relationship: SemanticRelationship) -> dict[str, Any]:
    return {
        "name": relationship.name,
        "from_dataset": relationship.from_dataset.name,
        "to_dataset": relationship.to_dataset.name,
        "relationship_type": relationship.relationship_type,
        "join_expression": relationship.join_expression,
    }


def base_object_for_change(model, workspace, change: SemanticCanvasChange):
    """Return the persisted object a change row overlays, or None for creates."""
    if change.change_type == SemanticCanvasChange.ChangeType.CREATE:
        return None
    object_type = change.object_type
    if object_type == SemanticCanvasChange.ObjectType.DATASET:
        return model.datasets.filter(id=change.object_uuid).first()
    if object_type == SemanticCanvasChange.ObjectType.FIELD:
        return (
            SemanticField.objects.filter(id=change.object_uuid, dataset__semantic_model=model)
            .select_related("dataset")
            .first()
        )
    if object_type == SemanticCanvasChange.ObjectType.RELATIONSHIP:
        return SemanticRelationship.objects.filter(
            id=change.object_uuid, workspace=workspace
        ).first()
    return None


def serialize_base(obj) -> dict[str, Any]:
    if isinstance(obj, SemanticDataset):
        return serialize_dataset_base(obj)
    if isinstance(obj, SemanticField):
        return serialize_field_base(obj)
    if isinstance(obj, SemanticRelationship):
        return serialize_relationship_base(obj)
    return {}
