import { useEffect } from "react"

// Cumulative ~2 minutes: the title is generated by a background worker that may
// first finish a job it already started, such as a data load.
export const TITLE_REFRESH_DELAYS_MS = [2000, 4000, 8000, 15000, 30000, 60000]

export interface TitleRefreshTrigger {
  threadId: string
  turn: number
}

/** Calls ``tick`` on the title-refresh schedule; returns a canceller. */
export function scheduleTitleRefresh(tick: () => void): () => void {
  let elapsed = 0
  const timers = TITLE_REFRESH_DELAYS_MS.map((delay) => {
    elapsed += delay
    return setTimeout(tick, elapsed)
  })
  return () => timers.forEach(clearTimeout)
}

/**
 * Refetch the thread list after a turn until the thread's generated title arrives.
 *
 * Header and sidebar both read the same store entry, so one refetch updates both.
 * Polling stops as soon as the title is no longer provisional, or the thread changes.
 */
export function useGeneratedTitleRefresh({
  workspaceId,
  threadId,
  titlePending,
  trigger,
  refresh,
}: {
  workspaceId: string | null
  threadId: string
  titlePending: boolean
  trigger: TitleRefreshTrigger | null
  refresh: (workspaceId: string) => Promise<void>
}) {
  useEffect(() => {
    if (!workspaceId || !titlePending || trigger?.threadId !== threadId) return
    return scheduleTitleRefresh(() => void refresh(workspaceId))
  }, [workspaceId, threadId, titlePending, trigger, refresh])
}
