# Generated by Django 5.2.11 on 2026-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_threadjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
