# Generated by Django 5.2.11 on 2026-05-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_thread_last_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadjob',
            name='error_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
