# Generated by Django 5.2.11 on 2026-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_threadjob_error_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
