# Generated by Django 5.2.11 on 2026-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_threadjob_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadjob",
            name="credential_failures",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
