# Generated by Django 5.2.11 on 2026-07-01 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_artifact_semantic_query_manifest_and_records'),
        ('chat', '0006_threadjob_started_at'),
        ('workspaces', '0005_add_view_schema_last_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, default='', max_length=203),
        ),
        migrations.AddField(
            model_name='thread',
            name='title_is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ThreadArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('mentioned', 'Mentioned'), ('attached', 'Attached')], default='mentioned', max_length=16)),
                ('message_id', models.CharField(blank=True, default='', max_length=128)),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_links', to='artifacts.artifact')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_links', to='chat.thread')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_artifact_links', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['thread', '-last_seen_at'], name='chat_thart_thread_seen'), models.Index(fields=['workspace', '-last_seen_at'], name='chat_thart_ws_seen')],
                'constraints': [models.UniqueConstraint(fields=('thread', 'artifact'), name='unique_thread_artifact_link')],
            },
        ),
    ]
