# Generated by Django 5.2.11 on 2026-09-29 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_threadjob_failure_phase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="is_shared",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="share_token",
        ),
    ]
