# Generated by Django 5.2.11 on 2026-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_remove_thread_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="turn_lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="turn_lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
