# Generated by Django 5.2.11 on 2026-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_thread_turn_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="title_source",
            field=models.CharField(
                choices=[
                    ("first_message", "First message"),
                    ("generated", "Generated"),
                    ("user", "User"),
                ],
                db_default="first_message",
                default="first_message",
                max_length=16,
            ),
        ),
    ]
