# Generated by Django 5.2.11 on 2026-10-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_backfill_thread_title_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRequest",
            fields=[
                (
                    "thread",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pending_request",
                        serialize=False,
                        to="chat.thread",
                    ),
                ),
                ("parts", models.JSONField(default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[("waiting", "Waiting"), ("claimed", "Claimed")],
                        default="waiting",
                        max_length=16,
                    ),
                ),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thread_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.threadjob",
                    ),
                ),
            ],
        ),
    ]
