# Generated by Django 5.2.11 on 2026-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_pending_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingrequest",
            name="flush_attempts",
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
