# Generated by Django 5.2.11 on 2026-10-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_pending_request_flush_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeStreamChunk",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("run", models.UUIDField()),
                ("text", models.TextField(blank=True, default="")),
                ("done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chat.thread",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["thread", "id"], name="chat_resumestream_thread_id")
                ],
            },
        ),
    ]
